Create Emission Chart
toriis-portal/toriis pull request #101
Opened 2023-04-02 00:10 UTC by 21xiaofanli

## Summary

Description of PR here...
Closes #85, Closes #22

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-04-08 01:13 UTC, zorazrr requested changes
The chart looks really cool 🚀!! Great work 🚀! 
Just some small nits and edge case handlings.

2023-04-08 01:13 UTC, zorazrr commented on src/components/Charts/EmissionBarChart.tsx
> +      data: Object.entries(source.data).map(([x, y], index) => ({
Nit. For unused variables like `x` in `[x, y]` here, the convention is to use an underscore, so `[_, y]` (or `[_x, y]`)

2023-04-08 01:13 UTC, zorazrr commented on src/components/Charts/EmissionBarChart.tsx
> +      data: Object.entries(source.data).map(([x, y], index) => ({
Noticed that, currently on hover it always shows "series-1" on the label. We can potentially give it a more descriptive naming by adding a `name: Emission Amount` to `series` (read Apex Chart doc for more!). Additionally, I wonder if a measurement unit would help in this case. Would recommend confirming with @jocelynxu01 on what to display here.

2023-04-08 01:13 UTC, zorazrr commented on src/components/Charts/EmissionBarChart.tsx
> +        y,
An edge case - some of the scope emissions may be `null` (so like, `scopeOne` and `scopeTwo` would exist but `scopeThree` might be missing), so we need to handle this situation. Currently it's throwing an error. 
![image](https://user-images.githubusercontent.com/61670566/230696932-92ca184d-9a72-4a77-b43e-9c43660f999d.png)

2023-04-12 17:51 UTC, zorazrr requested changes
Looks great! Some more clean ups, almost there!

2023-04-12 17:51 UTC, zorazrr commented on src/components/Card/ScopeCard.tsx
> +const ScopeCard: FC<{ children: React.ReactNode }> = ({ children }) => {
Let's rename this to `DataCard` since it is also used elsewhere for other charts!

2023-04-12 17:51 UTC, zorazrr commented on src/components/Card/ScopeCard.tsx
> +    <div className=" col-span-2 ml-20 rounded-xl bg-lightClementine p-4 font-inter text-base leading-snug">
Let's not use grid here, we prefer flex boxes! Additionally, things like `ml-20` should come from the parent component.

2023-04-12 17:51 UTC, zorazrr commented on src/components/Charts/EmissionBarChart.tsx
> +import type { Emission } from '@prisma/client'
Nit. Space after import.

2023-04-12 17:51 UTC, zorazrr commented on src/components/Charts/EmissionBarChart.tsx
> +const Chart = dynamic(() => import('react-apexcharts'), { ssr: false })
This is also an import so let's move this above interface!

2023-04-12 17:51 UTC, zorazrr commented on src/pages/company/[id].tsx
> +      {NonzeroEmission && (
Should be fine doing a simple `data.emission && (...` check here?

2023-04-12 17:51 UTC, zorazrr commented on src/pages/company/[id].tsx
> +          <div className="grid grid-cols-4 flex-col items-center justify-center align-middle">
As mentioned above, let's use flex box instead of grid for the page structure.

2023-04-12 17:51 UTC, zorazrr commented on src/server/api/routers/company.ts
> +
Now that we are accessing emission info through `getCompany`, we probably don't need this procedure right?

2023-04-12 17:51 UTC, zorazrr commented on src/pages/company/[id].tsx
> +      {NonzeroEmission && (
Noticed another `data.emission && (...` check on line 127, is it necessary to have 2 layers check here?

2023-04-12 17:51 UTC, zorazrr commented on src/pages/company/[id].tsx
> +            <ScopeCard>
Note to self: find out a cleaner way to handle these chunky paragraphs (potentially Contentful) on this page

2023-04-13 07:26 UTC, 21xiaofanli commented on src/pages/company/[id].tsx
> +      {NonzeroEmission && (
ohhh i did that bc jocelyn wanted everything to disappear if there was no data for scope but it was throwing errors if i didnt also add it in w line 127 as well

2023-04-13 07:46 UTC, 21xiaofanli commented on src/pages/company/[id].tsx
> +      {NonzeroEmission && (
nvm i saw everyone else just checked for the chart so i will just do that too

2023-04-13 18:56 UTC, zorazrr approved these changes

2023-04-13 18:57 UTC, merged