Company Details Contentful
toriis-portal/toriis pull request #102
Opened 2023-04-03 23:22 UTC by eeshabarua

## Summary

Working towards connecting Contentful API into the Company Details page.

Closes #88 

## Changes

- 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61480751/229647596-6315a4f3-321c-4f7b-9988-c5198df9fe53.png">

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-04-10 14:11 UTC, zorazrr requested changes
Nice work! Excited to see the company page coming together. 
There are some typing changes and edge cases to consider. 
Other than those, v cool!

2023-04-10 14:11 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      if (sectorEntries && Array.isArray(sectorEntries)) {
Here we can type cast `sectorEntries` to enforce a stronger type on it, so that we won't need this if statement here. Something like 
```js
const sectorEntries = (await contentClient.get('sector')) as SectorEntry[]
```
However, this may require us to change some things up for the `ContentWrapper` class (which was originally designed specifically for home page content, so some function return types may not fit everything), I can explain more during dev night.

2023-04-10 14:11 UTC, zorazrr commented on src/server/api/routers/company.ts
> +            company['sector'].charAt(0).toUpperCase() +
There is actually a [utils for enums file](https://github.com/toriis-portal/toriis/blob/main/src/utils/enums.ts) that could potentially make this conversion easier!

2023-04-10 14:11 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        sectorEntries.map((item: SectorEntry) => {
Maybe use a [filter](https://stackoverflow.com/questions/6237537/finding-matching-objects-in-an-array-of-objects) here instead of a map.

2023-04-10 14:11 UTC, zorazrr commented on src/server/api/routers/company.ts
> +            company['sector'].charAt(0).toUpperCase() +
Additionally, seems like `null` values of sector/industry is not handled here, so let's double check `null` cases, and also check with @jocelynxu01 on what we should display in cases of empty values.

2023-04-10 14:11 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      return [company, sectorEntry, industryEntry]
As suggested above, let's make this return an object!

2023-04-10 14:11 UTC, zorazrr commented on src/types/index.ts
> +  details: string
Hmmm I noticed that some sector details contains urls, so I wonder if we should make `details` a `richtext` field. Let's discuss more during dev night ;)~

2023-04-12 18:34 UTC, zorazrr requested changes
Great work! 
One major thing is the typing of the `get<T>` return, which will probably cause a lot of changes.

2023-04-12 18:34 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      if (!company || !company.sector) {
This should not be the case, even if `company.sector` is `null`, company itself may still exist.

2023-04-12 18:34 UTC, zorazrr commented on src/types/index.ts
> +  }
hmm... not sure why this is necessary?

2023-04-12 18:34 UTC, zorazrr commented on src/types/index.ts
> +  }
Ok I see now, check other comments for how to fix this.

2023-04-12 18:34 UTC, zorazrr commented on src/utils/content.ts
> +    return entries as unknown as T
```suggestion
    return entries.items.map((item) => item.fields) as unknown as T
```
This will fix a lot of weird typing issues and make things a lot cleaner in the `getCompany` procedure^^

2023-04-12 18:34 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        fields: {
These should not be necessary? Check comment on `content.ts`!

2023-04-13 02:52 UTC, eeshabarua commented on src/pages/company/[id].tsx
> +  }
<img width="761" alt="image" src="https://user-images.githubusercontent.com/61480751/231635911-248529a7-d515-4d61-a6fd-047ecc8c045d.png">
otherwise it gives me 'object is undefined'

2023-04-13 22:48 UTC, zorazrr approved these changes

2023-04-13 22:48 UTC, merged