Company Details Accordian
toriis-portal/toriis pull request #103
Opened 2023-04-03 23:24 UTC by lizageorge

## Summary

Description of PR here...
Closes #50 

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-04-07 02:33 UTC, zorazrr requested changes
Nice work! Just some small nits and clean-ups.

2023-04-07 02:33 UTC, zorazrr commented on src/pages/company/[id].tsx
> +      />
```suggestion
      {data.description && <CompanyDetailsAccordion content={data.description} />}
```

2023-04-07 02:33 UTC, zorazrr commented on src/pages/company/[id].tsx
> +      />
Let's move this below the tooltips!

2023-04-07 02:33 UTC, zorazrr commented on src/components/Accordions/CompanyDetailsAccordion.tsx
> +  const contentLengthTooLong = (content.match(/ /g) || []).length > maxWordCount
Nit. Could we do something like `const contentLengthTooLong = content.split(' ').length > maxWordCount`? Seems to be a bit more intuitive than `.match(/ /g)` and also aligns with what was used in `truncated` on line 20. We can even store the split result into an array and re-use it in both places. This also works though it's totally just a nit and up to you.

2023-04-07 02:33 UTC, zorazrr commented on src/components/Accordions/CompanyDetailsAccordion.tsx
> +    <div className="mb-10 rounded-[10px] border-[3px]  border-cobalt bg-lightBlue px-10 py-5">
```suggestion
    <div className="mb-10 rounded-xl border-[3px]  border-cobalt bg-lightBlue px-10 py-5">
```

2023-04-10 20:35 UTC, lizageorge commented on src/components/Accordions/CompanyDetailsAccordion.tsx
> +    <div className="mb-10 rounded-[10px] border-[3px]  border-cobalt bg-lightBlue px-10 py-5">
I think the exact radius from Figma was 10px, which was between `rounded-lg` and `rounded-xl`. But if we're sticking to TW standards instead I can make this change.

2023-04-10 22:54 UTC, zorazrr approved these changes
LGTM

2023-04-10 22:55 UTC, merged