Modal for Edit Page
toriis-portal/toriis pull request #113
Opened 2023-04-08 22:49 UTC by anthonycruzmacedo

## Summary
- Close #98 
- Modal to be used in Edit Page with the option to Leave Page (and possibly lose changes) or Continue Editing (remain on page)

<img width="402" alt="image" src="https://user-images.githubusercontent.com/90807954/230745680-90a5c0aa-c2a2-41e5-99ab-8f3df4e724c9.png">

## Changes

- Creating ```Modals``` folder under ```components``` folder
- Create ```LeaveContinueModal.tsx``` in Modals
- Add example/test usage in Landing.tsx for review purposes

2023-04-10 15:02 UTC, zorazrr requested changes
Great work! There are some general functionality and styling things to address.

2023-04-10 15:02 UTC, zorazrr commented on src/components/Modals/LeaveContinueModal.tsx
> +export const LeaveContinueModal: FC<ModalProps> = ({ onLeave, onContinue }) => {
Can we also extract the modal into a general component that takes in a child component, since it seems like that it will be used elsewhere. We can discuss more about this during dev night!

2023-04-10 17:17 UTC, anthonycruzmacedo commented on src/components/Modals/LeaveContinueModal.tsx
> +      <div className="flex h-[250px] w-[500px] flex-col items-center justify-evenly rounded-xl border-[1px] border-black py-8 text-center text-base">
Placed modal in div that takes up full screen, fixes modal to center (with scroll as well) and darkens background when popped up. Let me know if any of these are unwanted!

2023-04-17 19:47 UTC, zorazrr requested changes

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/GeneralModal.tsx
> +  isOpen: boolean // state variable for displaying modal
```suggestion
  isOpen: boolean
```

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/GeneralModal.tsx
> +  styles?: string
```suggestion
  className?: string
```

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/GeneralModal.tsx
> +  children?: JSX.Element | undefined | null
```suggestion
  children?: React.ReactNode
```

2023-04-17 19:47 UTC, zorazrr commented on src/components/index.ts
> +import LeaveConfirmationModal from './Modals/LeaveConfirmationModal'
Nit. Missing empty line.

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/GeneralModal.tsx
> +    : defaultModalStyles
This can be simplified a bit! Check out https://github.com/toriis-portal/toriis/blob/main/src/components/Text/Tag.tsx#L15.

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/LeaveConfirmationModal.tsx
> +    (window.location.href = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
LOL

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/LeaveConfirmationModal.tsx
> +    <>
Is this layer of `<></>` necessary

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/LeaveConfirmationModal.tsx
> +        <>
Is this layer of `<></>` necessary

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/LeaveConfirmationModal.tsx
> +              className="mx-1 h-8 w-3/5 rounded-full bg-clementine text-xs font-normal text-white min-[380px]:w-2/5 sm:w-2/5  sm:flex-[0_1_140px] sm:text-xs min-[800px]:text-base "
The two button styles overlap a lot, so we can use `clsx` to reduce the duplicate code a bit. For instance, see https://github.com/toriis-portal/toriis/blob/main/src/sections/company/TooltipGroup.tsx#L16.

2023-04-17 19:47 UTC, zorazrr commented on src/components/Modals/LeaveConfirmationModal.tsx
> +// 3. leave page functionality ONLY
Appreciate the comments! However, because the props are pretty straight-forward, it's probably safe to get rid of those?

2023-04-17 22:40 UTC, anthonycruzmacedo commented on src/components/index.ts
> +import LeaveConfirmationModal from './Modals/LeaveConfirmationModal'
Confused if there should be a an empty line or no

2023-04-17 22:53 UTC, anthonycruzmacedo commented on src/components/Modals/LeaveConfirmationModal.tsx
> +    (window.location.href = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
DEFAULT LINK DEFAULT LINK DEFAULT LINK

2023-04-19 00:20 UTC, daniel-moon32 approved these changes
Just adding on to the comments that Zora had, but looks good overall.

2023-04-19 00:20 UTC, daniel-moon32 commented on src/sections/home/Landing.tsx
> +          isOpen={modal} // state variable
I don't think you need these comments about the state variables

2023-04-19 00:20 UTC, daniel-moon32 commented on src/sections/home/Landing.tsx
> +            <div className="mb-6 p-4 lg:pr-14">
Does this div and the one above it need to be separated? I think they can be combined, but not 100% sure.

2023-04-19 00:20 UTC, daniel-moon32 commented on src/components/Modals/LeaveConfirmationModal.tsx
> +    (window.location.href = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
interesting I've seen this link before...

2023-04-19 00:20 UTC, daniel-moon32 commented on src/sections/home/Landing.tsx
> +          // onLeave={leave} // leave functionality ONLY, not setting state variable. Modal will handle
should this be commented out?

2023-04-19 00:20 UTC, daniel-moon32 requested changes
Whoops didn't mean to approve lol

2023-04-20 19:36 UTC, anthonycruzmacedo commented on src/sections/home/Landing.tsx
> +          // onLeave={leave} // leave functionality ONLY, not setting state variable. Modal will handle
Hi sorry anything in landing is just example usage, and commenting out onLeave was to see if default onLeave works

2023-04-20 19:36 UTC, anthonycruzmacedo commented on src/sections/home/Landing.tsx
> +          // onLeave={leave} // leave functionality ONLY, not setting state variable. Modal will handle
ie, will delete changes to Landing.tsx when ready to merge

2023-04-20 19:41 UTC, anthonycruzmacedo commented on src/components/index.ts
> +import LeaveConfirmationModal from './Modals/LeaveConfirmationModal'
Gonna take it as needs no empty line!

2023-04-20 20:06 UTC, zorazrr commented on src/sections/home/Landing.tsx
> -    <div className="flex flex-col items-center justify-center">
This file should not change :o

2023-04-20 20:41 UTC, zorazrr approved these changes

2023-04-20 21:24 UTC, daniel-moon32 approved these changes
Looks good!

2023-04-20 21:52 UTC, merged