Admin Table with Edit
toriis-portal/toriis pull request #115
Opened 2023-04-09 02:23 UTC by masgras2

## Summary

This PR adds an Admin List Table with Edit Mode. You'll never guess what issue it closes
Closes #94

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

2023-04-18 02:26 UTC, daniel-moon32 requested changes
Looks pretty good overall, but a couple stylistic issues. Feel free to ignore my comments if I'm missing context.

2023-04-18 02:26 UTC, daniel-moon32 commented on src/server/api/routers/user.ts
> +          return ctx.prisma.$runCommandRaw({
Could you explain to me why we need to use the $runCommand raw here? I think you could easily use prisma.user.update or prisma.user.upsert and then maybe you won't run in to that problem. I would need to test that out, but I think that's maybe a better way to do this.

2023-04-18 02:26 UTC, daniel-moon32 commented on src/components/Table/AdminListTable.tsx
> +                    deletePressed && 'text-lightGray',
I think you can convert this into an object and save it since you're using across multiple items so that it's
`
{'text-lightGray': deletePressed, 'text-black': !deletePressed}
`
and then you can add it to the clsx

2023-04-18 02:26 UTC, daniel-moon32 commented on src/components/Table/AdminListTable.tsx
> +  edit: boolean
Should this be canEdit for clarity that it's a boolean?

2023-04-18 02:26 UTC, daniel-moon32 commented on src/components/Buttons/PrimaryButton.tsx
> +  return link ? (
this is a pretty large conditional could you maybe change this to an if statement instead for clarity? I also think you could potentially extract each of these items into individual components, but you don't have to do that if you think that it's too annoying.

2023-04-18 05:00 UTC, zorazrr commented on src/pages/admin/management.tsx
> +      setUsersEmailUpdate([])
Confirmed with Joos that we want to go back to non-edit mode upon successful update, so let's add another callback here!

2023-04-18 05:04 UTC, zorazrr commented on src/server/api/routers/user.ts
> +          return ctx.prisma.$runCommandRaw({
Looks like Prisma does not support toggle boolean field according to this discussion: https://github.com/prisma/prisma/discussions/6102. But yes I think we could use Optimistic Concurrency Control :D here. That being, prisma query to find one with id, get the `shouldEmail` info, and another query to update the info. One advantage of raw query is it potentially allows updatemany toggle boolean without a loop, but looks like a `map` is still used here.

2023-04-18 05:18 UTC, zorazrr requested changes
Additionally, remember to merge main!

2023-04-19 20:57 UTC, masgras2 commented on src/components/Table/AdminListTable.tsx
> +                    deletePressed && 'text-lightGray',
This only applies to the first two <p> tags though, as the last one should have `text-medGray` by default instead of `text-black`. Even though I can't move it up a level to the <div>, should I still extract the component, given that it's used for two <p> tags?

2023-04-20 00:12 UTC, daniel-moon32 requested changes
Just a few more nitpicks that missed from last time, but overall looks really good! After you fix those you should be good to go!

2023-04-20 00:12 UTC, daniel-moon32 commented on src/components/Table/AdminListTable.tsx
> +                    'basis-1/6 text-base',
you can probably make this a little cleaner by using this syntax:
`'{'text-lightGray': deletePressed, 'text-medGray':!deletePressed `

2023-04-20 00:12 UTC, daniel-moon32 commented on src/server/api/routers/user.ts
> +        const currentEmailVal = await ctx.prisma.user.findUnique({
Nice work here! Really clean

2023-04-20 00:12 UTC, daniel-moon32 commented on src/server/api/routers/user.ts
> +            shouldEmail: !currentEmailVal?.shouldEmail,
hmm what's the behavior here when currentEmailVal is null? This seems like it could potentially have some undefined behavior.

2023-04-20 00:12 UTC, daniel-moon32 commented on src/pages/admin/management.tsx
> +              {'('}
Why is this split across 3 lines? I feel like you could potentially use stringbuilder notation
```{`( ${data?.length || 0} Results)`}```

2023-04-20 01:55 UTC, zorazrr requested changes
One thing - upon exiting edit mode let's also reset `shouldEmail` checkboxes!

2023-04-20 01:55 UTC, zorazrr commented on src/pages/admin/management.tsx
> +      setUsersToDelete([])
We also want to reset `shouldEmailUpdate` (and reflect those on the checkboxes) upon exiting edit mode.

2023-04-20 01:55 UTC, zorazrr commented on src/server/api/routers/user.ts
> +        })
Maybe throw an error here as well to check for `currentEmailVal`, then you won't need to worry about `currenEmailVal` being `null` in `user.update`.

2023-04-20 01:55 UTC, zorazrr commented on src/pages/admin/management.tsx
> +          <div className="-mb-[12px] flex basis-1/2 flex-row items-start justify-start gap-1">
Nit. Not sure if `basis-1/2` is really necessary here? 
![image](https://user-images.githubusercontent.com/61670566/233237743-f5192e07-a062-4768-80f7-3ca6e0c7e919.png)

2023-04-20 14:50 UTC, zorazrr requested changes
One final change and this should be good to go!! Really nice work :D

2023-04-20 22:11 UTC, daniel-moon32 approved these changes
Looks good just one small change and you can merge

2023-04-20 22:11 UTC, daniel-moon32 commented on src/components/Table/AdminListTable.tsx
> +        'flex h-[450px] flex-col items-center overflow-y-scroll rounded-xl border border-black shadow-[inset_0_4px_4px_rgba(0,0,0,0.25)]',
We don't want the scrollbar to show up when there isn't any overflow so you can do overflow-y-auto

2023-04-20 22:36 UTC, merged