Admin Nav Bar
toriis-portal/toriis pull request #119
Opened 2023-04-10 22:56 UTC by lizageorge

## Summary

Description of PR here...
Closes #118 

(old pr was associated with a branch of the wrong name and that bugged me)

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-04-17 05:41 UTC, zorazrr commented
There are some adjustments to the routes, see https://github.com/toriis-portal/toriis/pull/130. We are getting rid of 'csv'

2023-04-19 02:31 UTC, zorazrr requested changes
Nice work! One thing is that we ideally want everything to be handled within the component so that pages remain clean. There are some small styling changes to address as well. Other than that it looks good!

2023-04-19 02:31 UTC, zorazrr commented on src/pages/admin/index.tsx
> +              />
Let's make sure that the title is centered (it's a bit skewed due to uneven div width rn)! So you might want to make some adjustments to how the flex boxes are layed out.

2023-04-19 02:31 UTC, zorazrr commented on src/components/Nav/WebsiteManagementNavBar.tsx
> +                }`}
For consistency let's use `clsx` for conditions.

2023-04-19 02:31 UTC, zorazrr commented on src/pages/admin/website/content.tsx
> +  ]
Currently we are passing in the nav item information on the page level. Ideally, to keep pages clean, we want to handle all the routing and nav items within the `WebsiteManagementNavBar` component. You can detect `active` through router there (see https://github.com/toriis-portal/toriis/blob/main/src/components/Buttons/NavButton.tsx#L12 for a reference).

2023-04-19 02:31 UTC, zorazrr commented on src/pages/admin/website/data.tsx
> +  ]
Same thing as above, let's try to keep this on component level.

2023-04-19 02:31 UTC, zorazrr commented on src/pages/admin/index.tsx
> +          <div className="flex flex-row items-center justify-between border-b-[3px] border-cobalt px-10">
Could we make this a part of the `WebsiteManagementNavBar` as well? That way the nav bar layout will stay consistent throughout. It will also be cleaner if we could directly add Nav Bar as a component on pages!

2023-04-19 02:31 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
> +}
Nice addition here.

2023-04-19 02:31 UTC, zorazrr commented on src/pages/admin/index.tsx
Let's also add the nav bar to [Request Management Page](https://github.com/toriis-portal/toriis/blob/main/src/pages/admin/request/index.tsx) (see [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1346&t=Q2vT8v8ItNFp52hT-0))

2023-04-19 02:32 UTC, zorazrr commented
Also remember to merge w/ main :)

2023-04-20 15:17 UTC, lizageorge commented on yarn.lock
yea i ran npm intall by habit once and didn't fix it correctly :") good catch

2023-04-20 15:32 UTC, lizageorge commented on src/components/Nav/WebsiteManagementNavBar.tsx
> +        <BackButton />
Should I change the button name to match that too?

2023-04-20 22:18 UTC, lizageorge commented on src/components/Nav/WebsiteManagementNavBar.tsx
> +        <BackButton />
Nwm I checked with joos, it stays as "Back"

2023-04-21 03:30 UTC, zorazrr requested changes
Great work making it into one single component! 
Just some styling changes (flex box) + using path name instead of passing in props.

2023-04-21 03:30 UTC, zorazrr commented on src/components/Nav/AdminNavBar.tsx
> +              <div className={clsx('z-0 h-2', isActive && 'bg-clementine')} />
hmmm not exactly sure why this is a div, could be an underline text decoration?

2023-04-21 03:30 UTC, zorazrr commented on src/components/Nav/AdminNavBar.tsx
> +          console.log(path, '' + navItem.path, isActive)
```suggestion
```

2023-04-21 03:30 UTC, zorazrr commented on src/components/Nav/AdminNavBar.tsx
> +      <div className="mt-10 lg:-ml-24">
Not sure if `lg:-ml-24` is the best way to center the title, ideally we make use of flexbox. We can have three `div`s wrapping around back button, central element, and auth button, and do a `basis-1/3`.

2023-04-21 03:30 UTC, zorazrr commented on src/components/Nav/AdminNavBar.tsx
> +              <div className={clsx('z-0 h-2', isActive && 'bg-clementine')} />
Also it seems a bit too thick. Do check with design on this one though.

2023-04-21 03:30 UTC, zorazrr commented on src/components/Nav/AdminNavBar.tsx
> +    <div className="flex items-center justify-between border-b-[3px] border-cobalt px-10">
Could we make the nav bar thinner? If you feel like you need to modify the `HighlightedTitle` component for it to happen feel free to do so.

2023-04-21 03:30 UTC, zorazrr commented on src/pages/admin/management.tsx
> +        <AdminNavBar adminPage="adminManagement" />
As mentioned above, ideally we don't have to pass in additional props from page level, everything could potentially be handled by `useRouter`.

2023-04-22 17:02 UTC, lizageorge commented on src/components/Nav/AdminNavBar.tsx
> +              <div className={clsx('z-0 h-2', isActive && 'bg-clementine')} />
Yea, originally this was another offset thick underline like in the Highlighted Title, but then joos clarified it's just a normal underline. I'll fix that.

2023-04-22 22:10 UTC, zorazrr approved these changes

2023-04-22 22:11 UTC, merged