Update Tooltip Hover Feature
toriis-portal/toriis pull request #134
Opened 2023-04-17 22:42 UTC by eeshabarua

## Summary

Making a few lil bug fixes to update the Company Details Page.
Closes #121 

## Changes

- Tooltips now persist on hover of the Tooltip container
- Tooltip group flex wrap has spacing between first and second row
- NA -> N/A

## Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61480751/232625804-382877c1-b937-4ef4-8ba5-a31d1f30915c.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/61480751/232625945-bd20d341-0f48-4230-8163-3bad20ad94d6.png">

2023-04-19 00:13 UTC, daniel-moon32 requested changes
Looks good overall! Few things related to making sure the code is not repeated and more stylistically clean.

2023-04-19 00:13 UTC, daniel-moon32 commented on src/components/Tooltips/ToolTip.tsx
> +          if (
You should extract this into a separate function since you are reusing it below.

2023-04-23 14:01 UTC, zorazrr approved these changes

2023-04-24 21:54 UTC, daniel-moon32 commented on src/components/Tooltips/ToolTip.tsx
> +        className={clsx('bg-primary rounded', 'z-10 text-base text-black ')}
Nit, these shouldn't be separated by a comma if they aren't conditionally being changed.

2023-04-24 21:55 UTC, daniel-moon32 commented on src/pages/company/[id].tsx
> +        <div className="flex flex-col items-center ">
Remove space at the end of this string

2023-04-24 21:55 UTC, daniel-moon32 commented on src/components/Tooltips/ToolTip.tsx
> +              <div className=" font-semibold">{title}:</div>
Hmm I think this is leftover but there shouldn't be a random space before the font-semibold

2023-04-24 22:03 UTC, merged