Example Companies in Fossil Fuel Page
toriis-portal/toriis pull request #137
Opened 2023-04-17 23:15 UTC by lizageorge

## Summary

Description of PR here...
Closes #71 

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-04-25 17:14 UTC, zorazrr commented on src/components/Displays/Tabs/TabHeader.tsx
> +  }
Nit, but I like one-liners lol 
```js
const truncatedTitle = title.length > MAX_TITLE_LENGTH ? title.substring(0, MAX_TITLE_LENGTH) + '...' : title
```

2023-04-25 17:24 UTC, zorazrr commented on src/components/Displays/Tabs/Tabs.tsx
> +            <ArrowUpRightIcon className="inline h-4 pl-1" />
It'd be good to recycle components! See [ReadMoreButton](https://github.com/toriis-portal/toriis/blob/main/src/components/Buttons/ReadMoreButton.tsx).

2023-04-25 17:34 UTC, zorazrr commented on src/sections/fossil-fuel/DirtyIndustries.tsx
> +          </a>
This chunk can be simplified (see https://github.com/toriis-portal/toriis/blob/main/src/sections/company/TooltipGroup.tsx#L35).

2023-04-27 23:26 UTC, lizageorge commented on src/components/Displays/Tabs/Tabs.tsx
> +            <ArrowUpRightIcon className="inline h-4 pl-1" />
I saw that we had that, but the styling for that button is quite different and we don't need the logic, so I made my own - is that okay?

2023-04-27 23:31 UTC, lizageorge commented on src/sections/fossil-fuel/DirtyIndustries.tsx
> +  const contentfulOptions = {
This would make a few type handling things easier, but I assumed that the Tabs component had to be reusable. I mean ig it doesn't matter now cause we're so close to the end :") but should I change it to be less reusable?

2023-04-28 02:25 UTC, zorazrr commented on src/components/Displays/Tabs/Tabs.tsx
> +            <ArrowUpRightIcon className="inline h-4 pl-1" />
It's still good to re-use Ig in case we want to change the button some day and the change would propogate. You can customize the read more button a bit to fit the styling here, for instance, when there is no link, do not display the arrow icon.

2023-04-28 02:27 UTC, zorazrr commented on src/components/Displays/Tabs/Tabs.tsx
> +            <ArrowUpRightIcon className="inline h-4 pl-1" />
Jk yea I didn't realize the styling was different.

2023-04-28 02:27 UTC, zorazrr commented on src/sections/fossil-fuel/DirtyIndustries.tsx
> +  const contentfulOptions = {
Ok yea let's keep it as is for now.

2023-04-29 22:51 UTC, lizageorge commented on src/sections/fossil-fuel/DirtyIndustries.tsx
> +          </a>
sorry, i'm a bit confused on the relevance of the bit you linked - like I should be separating these options to something in `src/utils/contentfulOptions.txt`?

2023-04-29 23:29 UTC, lizageorge commented on src/components/Displays/Tabs/TabHeader.tsx
> +  const MAX_TITLE_LENGTH = 5
<img width="697" alt="image" src="https://user-images.githubusercontent.com/20449375/235328145-2f5d5e16-51b5-4fd6-8260-9add12929c09.png">

this won't work with a view as small as mobile, I think that will need a different design. But jocelyn said this is fine for now.

2023-04-29 23:33 UTC, lizageorge commented
Also added filler text to contentful for non-exon companies.

2023-04-30 01:48 UTC, masgras2 requested changes
Just one small thing, then lgtm!

2023-04-30 01:48 UTC, masgras2 commented on src/components/Displays/Tabs/Tabs.tsx
> +interface TabDetails {
This interface gets reused in DirtyIndustries.tsx. You probably can export it here and import it there to avoid having to re-declare the same interface in a different spot.

2023-04-30 01:48 UTC, masgras2 commented on src/components/Displays/Tabs/Tabs.tsx
> +interface TabDetails {
It could also probably be put in types/index.ts

2023-04-30 03:23 UTC, zorazrr approved these changes
lgtm

2023-04-30 16:23 UTC, merged