Standardize Font Sizes
toriis-portal/toriis pull request #146
Opened 2023-04-20 22:03 UTC by anthonycruzmacedo

## Summary

- Closes #83 
- Standardize fonts across site to fit h1, h2, h3, body bold, regular body 1, regular body 2 as defined on figma and below

style | font-family | font-style | font-weight | font-size | line-height
--- | --- | --- | --- |--- |---
Seconds | 301 | 283 | 290 | 286 | 289 

## Changes
-

## Screenshots
-

2023-04-26 18:31 UTC, zorazrr requested changes
Nice work!! The site is looking much cleaner :D. 
Some naming and styling cleanups!

2023-04-27 19:18 UTC, anthonycruzmacedo commented on src/styles/globals.css
> +  .t3 {
replaced t with header-, renamed bb to body-bold, r1/r2 to body-normal/body-small

2023-04-27 19:19 UTC, anthonycruzmacedo commented on src/styles/globals.css
> +  .r1 {
Placed in body-bold in _app.tsx as default font option

2023-04-27 19:20 UTC, anthonycruzmacedo commented on src/components/Buttons/BackButton.tsx
> +          'bb flex w-fit place-content-center items-center justify-center truncate p-4 font-inter',
removed repetitive uses of font-x, font-[x], text-x, text-[x], some remain to override default font styles in specific cases

2023-04-27 19:21 UTC, anthonycruzmacedo commented on src/styles/globals.css
> +    @apply font-inter text-base font-normal leading-[19px];
removed line height styles from globals.css font options

2023-04-27 19:21 UTC, anthonycruzmacedo commented on src/components/Selects/SearchBar.tsx
> +            className="bb underline-offset-6 ml-6 flex items-center justify-center rounded-full bg-black py-1 px-4 text-white underline"
removed all instances of body-bold

2023-04-27 22:43 UTC, zorazrr requested changes

2023-04-27 22:43 UTC, zorazrr commented on src/components/Accordions/CompanyDetailsAccordion.tsx
> +        ' rounded-[10px] border-[3px] border-cobalt bg-lightBlue px-10 py-5',
```suggestion
        'rounded-[10px] border-[3px] border-cobalt bg-lightBlue px-10 py-5',
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
> +          ' flex w-fit place-content-center items-center justify-center truncate p-4',
```suggestion
          'flex w-fit place-content-center items-center justify-center truncate p-4',
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Buttons/LoadMoreButton.tsx
> +        ' rounded border-2 border-solid border-clementine bg-white',
```suggestion
        'rounded border-2 border-solid border-clementine bg-white',
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Table/AdminListTable.tsx
> +  clsx('basis-1/3 truncate ', {
```suggestion
  clsx('basis-1/3 truncate', {
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +                    <span className="">{key}</span>
```suggestion
                    <span>{key}</span>
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +              ' overflow-hidden whitespace-nowrap': isFilter,
```suggestion
              'overflow-hidden whitespace-nowrap': isFilter,
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +          ' flex w-full items-center overflow-hidden rounded-full border border-solid',
```suggestion
          'flex w-full items-center overflow-hidden rounded-full border border-solid',
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Nav/SecondaryNavBar.tsx
> +                className={clsx(navStyle, '')}
```suggestion
                className={navStyle}
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Text/ShadowTitle.tsx
> +        ' header-3 w-fit rounded-full bg-white',
```suggestion
        'header-3 w-fit rounded-full bg-white',
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Text/ShadowTitle.tsx
> +      <p className="text-darkTeal ">{text}</p>
```suggestion
      <p className="text-darkTeal">{text}</p>
```

2023-04-27 22:43 UTC, zorazrr commented on src/components/Text/Tag.tsx
> +        ' truncate',
Merge 2 lines together!

2023-04-27 22:43 UTC, zorazrr commented on src/components/Tooltips/ToolTip.tsx
> +                <p className="font-bold">{title}:</p>
Title should be bolded.

2023-04-28 01:45 UTC, merged