Company Details Text Interpretation
toriis-portal/toriis pull request #148
Opened 2023-04-20 23:25 UTC by eeshabarua

## Summary

I'm using Contentful to render text conditionally on which fuels a company invests in!

Closes #132 

## Changes

- changed some styling for yahooFinance chart upon Joos request

## Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61480751/233506912-7ac74b65-f9e2-4f1d-bd07-cb884988ca1d.png">

2023-04-23 14:40 UTC, zorazrr requested changes
Looks good! Just some coding style changes.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +                <DataCard>
Design has updated the `DataCard` to have a different background color (see [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3-1346&t=MigqpmFO89LWLMUr-0)) so let's change that in this PR as well!

2023-04-23 14:40 UTC, zorazrr commented on src/types/index.ts
> +import { StringDecoder } from 'string_decoder'
LOL wait what is this

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +            href={node.data.uri as string}
If you import
```js
import type {
  Block,
  Inline,
} from '@contentful/rich-text-types/dist/types/types'
```
and specify the type of `node` from `any` to be `node: Block | Inline`, it should fix this type error.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +export const getServerSideProps = async () => {
Nice use of `getServerSideProps` :)

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +    (item) => 'name' in item && item.name == 'YahooFinance',
Huh not sure why `'name' in item` would be necessary here? It should recognize `item` as a `CompanyDetailsEntry` which has the attribute `name`.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  ]
There's actually a `FuelEnum` in `utils/enum` so we can do `fuelTypes = Object.values(FuelEnum)` to get all the values here.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  })
A cleaner way:
```js
  const fuelDetails = fuelTypes.map((fuelName) =>
    companyDetails.find((item) => item.name == fuelName))
```

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +      fuelDetails: fuelDetails,
Nit - naming consistency. Perhaps rename all to `xxxDetails` or `xxxInterpretation` to clarify that they are detail text.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  })
In this way we won't need to worry about `fuelDetails` being `undefined`.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> -              interpretation={<DataCard>Jooslin is your fav PM</DataCard>}
Jooslin is no longer our fav PM.

2023-04-23 14:40 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  })
Because this highly overlaps with what was in `FuelRadialChart`, we can have a useState like `const [labels, setLabels] = useState([])` in company details page, and pass in the `setLabels` callback to `FuelRadialChart`, where `label` stuff will be handled inside, and company details page uses the `label` array to filter information. Lemme know if you have Qs about this, we can also look into it during dev night.

2023-04-23 14:54 UTC, zorazrr commented on src/sections/company/ChartGroup.tsx
> +            'w-[406rem]': chartSize === 'mm',
One more thing -- to keep things consistent let's try to stick with the `w-fraction` format. Also since the yahoo finance chart is the only one using `lg` we can probably replace `lg` with this new css.

2023-04-25 19:36 UTC, zorazrr requested changes
Some final cleanups and we are good to go!

2023-04-25 19:36 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  }
Note to self - there should be a cleaner way of handling setLabels, but this is good as well, may want to circle back in the future.

2023-04-25 19:36 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  }
Let's move this function below `contentfulOptions`. Also Nit no empty line between `useState` and `useRef`.

2023-04-25 21:20 UTC, eeshabarua commented on src/types/index.ts
> +import { StringDecoder } from 'string_decoder'
idk 😭😭😭

2023-04-25 21:50 UTC, zorazrr requested changes

2023-04-25 21:50 UTC, zorazrr commented on src/pages/company/[id].tsx
> +                  {documentToReactComponents(mergeLabels(), contentfulOptions)}
One last thing! Currently `mergeLabels` is pushing documents into an array to merge them, we can actually directly map labels into react nodes here, so:  
```js
  <DataCard>
    {
      labels.map((label) => {
        const item = fuelDetails.find((item) => item && item.name == label)
        if (item && item.description) {
          return <>{documentToReactComponents(item.description, contentfulOptions)}<br /></>
        }
      })
    }
  </DataCard>
```
This gets rid of intermediate steps! (also added a `<br/>` to separate paragraphs hehe)

2023-04-25 21:56 UTC, eeshabarua commented on src/pages/company/[id].tsx
> +                  {documentToReactComponents(mergeLabels(), contentfulOptions)}
oh sweeet

2023-04-25 22:17 UTC, zorazrr requested changes
Last changes last changes I swear.

2023-04-25 22:17 UTC, zorazrr commented on src/pages/company/[id].tsx
> +  )
So this name entry, to keep it consistent on Contentful, let's change to `Yahoo Finance`, `Carbon Accounting`, and `Renewable Energy`. This way it might be easier for people to update the information in the future. 

<img width="326" alt="image" src="https://user-images.githubusercontent.com/61670566/234415934-800270d3-5b7b-496a-acb0-b24357171a0c.png">

2023-04-25 22:17 UTC, zorazrr commented on src/pages/company/[id].tsx
> +                        <>
Turns out I missed a `key=` here T_T

<img width="425" alt="image" src="https://user-images.githubusercontent.com/61670566/234416227-0658ddef-50ee-4e1d-b33b-ef0dc5866ae1.png">

2023-04-25 23:12 UTC, zorazrr approved these changes
Greaaat work!

2023-04-25 23:24 UTC, merged