Institutional Divestment Link Section
toriis-portal/toriis pull request #15
Opened 2023-02-20 23:29 UTC by lizageorge

## Summary

Description of PR here...
Closes #12

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-02-23 20:32 UTC, zorazrr requested changes
The component looks really clean! There are some small changes and updates.

2023-02-23 20:32 UTC, zorazrr commented on src/components/LinkDisplay.tsx
> +          <a
Let's use [`<Link>` from NextJs](https://nextjs.org/docs/api-reference/next/link) here! It does some heavy-lifting and is good for SEO.

2023-02-23 20:32 UTC, zorazrr commented on src/components/LinkDisplay.tsx
> +const links: Pair[] = data.links as Pair[]
Nit: the type casting `as Pair[]` seems to be redundant here.

2023-02-23 20:32 UTC, zorazrr commented on src/components/LinkDisplay.tsx
> +        <h1 className="text-lg font-semibold text-darkTeal ">
Let's match font sizes with Figma designs here! Titles should have size `28px` and body-text is `18px`. Also for body-text, since it will be used throughout, it would be good to define it in [_app.tsx](https://github.com/toriis-portal/toriis/blob/main/src/pages/_app.tsx).

2023-02-23 20:32 UTC, zorazrr commented on tailwind.config.cjs
> +        cobalt: '-8px 8px 0px 0px rgba(15, 129, 232, 1)',
Nice customized style config!

2023-02-23 20:32 UTC, zorazrr commented on src/components/LinkDisplay.tsx
> +            {pair.text}
In addition to text, there has been some updates on [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=wE13iS2xApPqvBjx-0) to include an icon. We can use [Hero Icons](https://heroicons.com/).

2023-02-23 20:32 UTC, zorazrr commented on src/info/instDivestment.json
> +{
Let's move this file as a nested-json object in [home.json](https://github.com/toriis-portal/toriis/blob/main/src/info/home.json) so that the info folder matches the page structures.

2023-02-23 23:08 UTC, lizageorge commented on src/info/instDivestment.json
> +{
so home.json would be one big object with one field called instDivestment that contains this link array?

2023-02-24 06:14 UTC, daniel-moon32 requested changes
Make sure to remove the package-lock since we're using yarn instead of npm. Otherwise looks pretty good!

2023-02-24 06:14 UTC, daniel-moon32 commented on src/components/LinkDisplay.tsx
> +              // to open link in new tab:
I don't think this comment is necessary

2023-02-24 06:14 UTC, daniel-moon32 commented on src/components/LinkDisplay.tsx
> +        <h1 className="text-3xl text-darkTeal ">
The header classes don't change anything with tailwind so you should be using just the text-3xl class with a p tag instead

2023-02-25 06:22 UTC, daniel-moon32 approved these changes
Looks good! Just a minor nitpick, but feel free to ignore if you think I'm wrong.

2023-02-25 06:22 UTC, daniel-moon32 commented on src/components/LinkDisplay.tsx
> +interface Pair {
Bit of a nitpick so I'll leave it up to you whether you want to actually change this, but I think the name pair isn't entirely clear from just the name. Maybe something that specifies that it's a pair of link and text

2023-02-25 22:50 UTC, zorazrr commented on src/components/LinkDisplay.tsx
> +          Institutional Divestment Links
Looks like we will be re-using this title style (see [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1243&t=xoxfLqHVrUQehqnO-0)), so let's extract this into a separate component!

2023-02-27 07:26 UTC, lizageorge commented on src/components/LinkDisplay.tsx
> +          Institutional Divestment Links
I couldn't find where else this style will be reused, so i'm just going to make a component that takes in text. Let me know if the interface will be more useful with anything else customized! I just can't find where it's supposed to be used.

2023-02-27 15:34 UTC, zorazrr requested changes
🚀 This is looking good! Just some yarn/npm stuff and nits to address. 🚀

2023-02-27 15:34 UTC, zorazrr commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@babel/runtime/-/runtime-7.20.13.tgz"
This looks like another yarn/npm thing. This file should not be changed. I wonder if deleting this file and then run `yarn install` again would solve this issue.

2023-02-27 15:34 UTC, zorazrr commented on src/components/ShadowTitle.tsx
> +    <div className="relative -top-12 z-10 rounded-full border-4 border-cobalt bg-white px-14 py-4 font-semibold shadow-cobalt">
`relative -top-12` seems to be something that is specific to the link display div, can we remove it here (and instead we could add a wrapper in `LinkDisplay.tsx`)? Additionally, let's add `w-fit`. 

Also my bad I did not realize that the figma link did not link to the correct section, but this is where we will be re-using the component: 
![image](https://user-images.githubusercontent.com/61670566/221606836-ee54185a-488d-40f5-b58f-03206fc81a69.png)

2023-02-27 15:34 UTC, zorazrr commented on src/components/ShadowTitle.tsx
> +interface InputProps {
```suggestion
interface TitleProps {
```

2023-02-27 15:34 UTC, zorazrr commented on src/components/ShadowTitle.tsx
> +const ShadowTitle: FC<InputProps> = ({ text }) => {
```suggestion
const ShadowTitle: FC<TitleProps> = ({ text }) => {
```

2023-02-27 16:08 UTC, zorazrr commented on src/components/ShadowTitle.tsx
> +    <div className="relative -top-12 z-10 rounded-full border-4 border-cobalt bg-white px-14 py-4 font-semibold shadow-cobalt">
Jk! These are such small changes, I could probably take care of those, don't worry about it!

2023-02-27 18:36 UTC, merged