Display sector environmental grade
toriis-portal/toriis pull request #158
Opened 2023-04-27 23:21 UTC by lizageorge

## Summary

Display sector environmental grade in company page tooltip
Closes #66 

## Changes

- Connected to DB with pymongo,  pulled Company and ESG collection
- Calculated median ESG grade per sector (rounding median index down when even number of grades)
- Added these grades to Contentful (adjusted contentful names/repo enum, and sectorEntry type)
- Conditionally display tooltip with sector average grade

## Screenshots
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/20449375/235010537-a3c5178f-d547-4809-bf24-72475fa95eea.png">

Sent the full notebook I used to find these grades to Zora, but here's the pipeline with the actual important stuff
```
pipeline = [
    {
        "$lookup":{
            "from": "Company",
            'localField' : 'companyId',
            'foreignField' : '_id',
            'as' : 'company'
        }
    },
    {
       "$unwind": "$company"
    },
    {
        "$project": {
            "environmentGrade": 1,
            "sector": "$company.sector"
        }
    },
    {
        "$group": {
            "_id": "$sector",
            "environmentGrades": {
                "$push": "$environmentGrade"
            }
        }
    },
    {
        "$project": {
            "sector": 1,
            "environmentGrades": {
                "$sortArray": {
                    "input": "$environmentGrades",
                    "sortBy": 1
                }
            },
            "size": { "$size": [ "$environmentGrades" ] }
        }
    },
    {
        "$project":{
            "sector": 1,
            "environmentGrades": 1,
            "middlePoint": { "$trunc": { "$divide": ["$size", 2] } }, # rounding down med index when environmentGrades has even length
        }
    },
    {
        "$project": {
            "sector": 1,
            "environmentGrades": 1,
            "medianValue": { "$arrayElemAt": ["$environmentGrades", "$middlePoint"] },
        }
    },
    # 
]
```

2023-04-28 22:50 UTC, zorazrr requested changes

2023-04-28 22:50 UTC, zorazrr commented on src/sections/company/TooltipGroup.tsx
> +              also addresses
Can we add this chunk to Contentful as well?

2023-04-29 23:11 UTC, lizageorge commented on src/sections/company/TooltipGroup.tsx
> +              also addresses
should i make a new content type for this? or just add it to the "info" type?

2023-04-30 00:37 UTC, zorazrr approved these changes
lgtm

2023-04-30 00:39 UTC, merged