Institutional Divestment List Text Section
toriis-portal/toriis pull request #16
Opened 2023-02-21 00:13 UTC by anthonycruzmacedo

## Summary
- see issue #11

## Changes

## Screenshots

2023-02-23 20:56 UTC, zorazrr requested changes
The list looks really cool! Some things to address: 
- Variable naming 
- Json data storage change 
- Not exactly sure why `src/components/DivestmentList.tsx` was commented out? 
- `.env.example` should not be deleted 
Other than those it looks good!

2023-02-23 20:56 UTC, zorazrr commented on src/components/NumberCircle.tsx
> +const NumberCircle: FC<props> = ({ val }) => {
For this component, instead of having two `div`s overlapping, it might be cleaner to take advantage of the box-shadow property in css. [Liza's PR](https://github.com/toriis-portal/toriis/blob/3055ad79df8d6f0eb86b87762918255db5b5ba31/tailwind.config.cjs#L7) is doing something similar.

2023-02-23 20:56 UTC, zorazrr commented on src/components/HighlightedTitle.tsx
> +interface props {
Would recommend something like `TitleProps` as the interface name here, same goes for the other props.

2023-02-23 20:56 UTC, zorazrr commented on tailwind.config.cjs
> +
```suggestion
```

2023-02-23 20:56 UTC, zorazrr commented on src/info/home.json
> +  "divestment-strings": {
Let's store the information here as an array of strings (will offer more flexibility in case we ever want to add data), something like 
```
"divestment-strings": ["Reducing...", "Being...", "and..."]
```
Interfaces and structures in other components may need to be changed accordingly.

2023-02-23 20:56 UTC, zorazrr commented on src/sections/InstitutionalDivestments.tsx
> +          {strings &&
Because we are retrieving static info that is not from the backend, `strings` is guaranteed to exist, so while `strings &&` is a nice layer of protection, it might be redundant here.

2023-02-24 05:45 UTC, daniel-moon32 requested changes
A couple small things with flexbox. Otherwise looks really great!

2023-02-24 05:45 UTC, daniel-moon32 commented on .env.example
> +GOOGLE_CLIENT_SECRET=""
Remove newline from file

2023-02-24 05:45 UTC, daniel-moon32 commented on src/components/ListItem.tsx
> +      <tr className="my-3 ml-6 flex items-center">
Ideally you would just use flexbox included with tailwind (Ask me if you need a refresher)

2023-02-24 05:45 UTC, daniel-moon32 commented on tailwind.config.cjs
> +      //Arial and Roboto are there to be other sans-serif
I don't think you need to comment this. This is implied to begin with

2023-02-24 05:45 UTC, daniel-moon32 commented on src/sections/InstitutionalDivestments.tsx
> +      <table className="flex-column items-start">
Again I don't think you need to use <ul> or <ol> instead of a table here or just use divs with flexbox

2023-02-24 05:45 UTC, daniel-moon32 commented on src/sections/InstitutionalDivestments.tsx
> +  [x: string]: string
This is some typescript wizardry that's a bit sus.  I think you need to type homedata and the infer the type from there

2023-02-24 05:45 UTC, daniel-moon32 commented on src/sections/InstitutionalDivestments.tsx
> +          {Object.keys(strings)?.map((k) => (
you should probably name 'k' something different

2023-02-24 15:17 UTC, zorazrr commented on src/sections/InstitutionalDivestments.tsx
> +  [x: string]: string
+1 maybe make a new folder named `types` under `src` and define an overall interface for the homepage json data.

2023-02-24 19:38 UTC, anthonycruzmacedo commented on tailwind.config.cjs
> +      //Arial and Roboto are there to be other sans-serif
Pulled this change in from another branch, will delete comments

2023-02-24 19:48 UTC, anthonycruzmacedo commented on src/sections/InstitutionalDivestments.tsx
> +  [x: string]: string
Typing homedata returns Object but no longer need this interface because I am using an array of strings now, and not a json object map

2023-02-24 23:58 UTC, daniel-moon32 requested changes
Looks a lot better! Just some small things to change related to the classnames

2023-02-24 23:58 UTC, daniel-moon32 commented on src/components/ListItem.tsx
> +      <div className="my-3 ml-6 flex items-center">
Much better! Nice work here

2023-02-24 23:58 UTC, daniel-moon32 commented on src/components/ListItem.tsx
> +          <p>{listContent}</p>
Just a bit of a nitpick but I think you should specify the font stuff at the p level not at the div level

2023-02-24 23:58 UTC, daniel-moon32 commented on src/components/NumberCircle.tsx
> +      <div className="flex h-12 w-12  items-center justify-center rounded-3xl border-2 border-cobalt bg-white text-center font-klima text-3xl font-bold text-cobalt shadow-circleCobalt">
same thing as before the text stuff should be applied to the text tag not the div above it

2023-02-24 23:58 UTC, daniel-moon32 commented on src/sections/InstitutionalDivestments.tsx
> +        <div className="pb-10 text-left text-2xl font-bold">
Having to apply the text settings at a div above it seems like a bit of an anti-pattern (I'm curious to know what @zorazrr  thinks)

2023-02-24 23:58 UTC, daniel-moon32 commented on src/pages/index.tsx
> +import InstitutionalDivestments from '../sections/InstitutionalDivestments'
I'm not 100% sure about this but I think this should be going to the app.tsx not the index.tsx

2023-02-25 01:07 UTC, zorazrr commented on src/pages/index.tsx
> +import InstitutionalDivestments from '../sections/InstitutionalDivestments'
I think he is just putting it here as a display placeholder, he'll delete when we merge.

2023-02-25 01:11 UTC, zorazrr commented on src/sections/InstitutionalDivestments.tsx
> +        <div className="pb-10 text-left text-2xl font-bold">
+1 should define font size in `HighlightedTitle` instead, also according to Figma the font-size should be `32px`.

2023-02-25 01:34 UTC, daniel-moon32 approved these changes
Looking really good! (I would wait for Zora to also get a chance to review before merging tho)

2023-02-25 01:34 UTC, daniel-moon32 commented on src/components/HighlightedTitle.tsx
> +        <p className="relative z-10 font-klima text-2xl font-bold">{title}</p>
Beautiful!

2023-02-25 01:51 UTC, zorazrr commented on tailwind.config.cjs
> +        cobalt: '-8px 8px 0px 0px rgba(15, 129, 232, 1)',
```suggestion
```

2023-02-25 01:54 UTC, zorazrr reviewed
Can you do one last check to see if your font sizes match the ones on Figma? Then remove the place holder in `index` and we are good to go 🎉!

2023-02-25 04:35 UTC, anthonycruzmacedo commented on src/components/HighlightedTitle.tsx
> +        <p className="relative z-10 font-klima text-2xl font-bold">{title}</p>
no u

2023-02-27 17:19 UTC, zorazrr approved these changes

2023-02-27 17:21 UTC, merged