Create Footer
toriis-portal/toriis pull request #160
Opened 2023-04-28 03:22 UTC by amit-sawhney

## Summary

Creates the footer in a somewhat responsive way. 
Closes #156 

## Changes

- Add social icon components to assets folder
- Add footer logic

## Screenshots

<img width="1728" alt="Screen Shot 2023-04-27 at 10 21 29 PM" src="https://user-images.githubusercontent.com/66758185/235046729-579c126b-999a-4800-8cbc-fc6bac40ffb8.png">

2023-04-28 03:23 UTC, ajain1921 commented
hmm im not sure react is the best choice for this PR. would u mind rewriting in rust?

2023-04-28 03:24 UTC, amit-sawhney commented
I apologize you are right.

2023-04-28 03:26 UTC, zorazrr commented
...

2023-04-28 03:31 UTC, amit-sawhney commented
@ajain1921 I have addressed your changes

2023-04-28 03:32 UTC, ajain1921 commented
> @ajain1921 I have addressed your changes

LOL WHAT??? HOW DID U EVEN MAKE THIS?? WHY DID THIS SUCCESSFULLY DEPLOY? SO MANY QUESTIONS...

2023-04-28 14:00 UTC, zorazrr requested changes
🐐

2023-04-28 14:01 UTC, zorazrr commented on src/components/Icon/FacebookIcon.tsx
Also is it me or is the Facebook icon smaller than the other ones.

2023-04-28 14:06 UTC, zorazrr commented on src/components/Footer/Footer.tsx
> +                href: 'https://www.instagram.com/secsillinois/',
This link does not work?? Should it be https://www.instagram.com/secsuiuc/?

2023-04-28 20:35 UTC, amit-sawhney commented on src/pages/home/index.tsx
> +        <Footer />
wait there isn't just one home page for all of your main pages 😭

2023-04-28 20:35 UTC, amit-sawhney commented on src/components/Icon/FacebookIcon.tsx
it is, but the icon itself is the same size, so wasn't sure, let me see if i can fix

2023-04-28 20:36 UTC, amit-sawhney commented on src/components/Footer/Footer.tsx
> +                href: 'https://www.instagram.com/secsillinois/',
OH MY BAD I FORGOT TO ACTUALLY GO FIX THE LINKS

2023-04-29 01:00 UTC, zorazrr approved these changes

2023-04-29 01:02 UTC, merged