Secondary Navbar
toriis-portal/toriis pull request #17
Opened 2023-02-21 00:32 UTC by eeshabarua

## Summary

Creating a cool sticky nav bar to scroll to different parts of the page!

Closes #6 

## Changes

- Implement React Scroll
- Fix Tiny CSS Things

## Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61480751/220217828-006fe7c7-49a8-4daf-8017-22c60f3797dd.png">

2023-02-23 23:45 UTC, eeshabarua commented
I'm having the same color issue as Xiaofan, I used the template orange color in the meantime.

2023-02-23 23:59 UTC, eeshabarua commented
<img width="165" alt="image" src="https://user-images.githubusercontent.com/61480751/221058626-efe6fed2-70d3-41fd-a7bd-eac1f2de944a.png">
Also, not sure if we want this hover functionality without the anchor. I can delete if not!

2023-02-24 15:12 UTC, zorazrr requested changes
The scrolling animation is looking fire!!!! 
One major thing is to make sure you use `yarn` instead of `npm`, so the `package-lock.json` should not be here. Additionally, we want to pass in nav items as props. Other than that, it's looking good, just some small styling changes.

2023-02-24 15:12 UTC, zorazrr commented on src/components/SecondaryNavBar.tsx
> +const NavBar: FC = () => {
Nit. Rename to `SecondaryNavBar`. 

Additionally, because we are reusing this nav bar in other pages as well, it would be great if we can extract things a bit here, so that instead of hard-coding the nav item strings, we could pass them in (maybe as an array of strings) as props!

2023-02-24 15:12 UTC, zorazrr commented on src/info/home.json
> +  "secondaryNavText": [
As mentioned above, we should pass this in as a prop to the secondary nav bar component!

2023-02-24 15:12 UTC, zorazrr commented on src/styles/globals.css
> +  text-decoration-color: orange;
You mentioned the color issue in comments: color definitions in Tailwind config doesn't transfer into this traditional CSS definition. So what you could do is either hardcoding the hexcode, or define CSS variables as in this [StackOverflow Post](https://stackoverflow.com/questions/64872861/how-to-use-css-variables-with-tailwind-css#:~:text=Armando%27s%20answer%20didn%27t%20work%20for%20me%20but%20with%20this%20change%20it%20did%20work.).

2023-02-24 15:12 UTC, zorazrr commented on src/components/SecondaryNavBar.tsx
> +                  className="no-underline hover:underline hover:underline-offset-8"
Let's give the hover an orange color as well (same as active class styles)! Additionally, we might want to add a [`cursor-pointer`](https://tailwindcss.com/docs/cursor) to indicate that this item is clickable.

2023-02-27 07:15 UTC, lizageorge requested changes

2023-02-27 07:15 UTC, lizageorge commented on src/components/SecondaryNavBar.tsx
> +            <ul className="flex space-x-8 p-4 text-sm text-white ">
The Figma has these links styled as 18px, but Tailwind's `text-sm` is 14px - could you remove this?
On Zora's suggestion, I had wrapped the whole body in a custom font-size class to be 18px in my branch, so once that's merged in all body text will automatically be 18px.
tldr; you don't need to specify font size here

2023-02-27 07:15 UTC, lizageorge commented on src/components/SecondaryNavBar.tsx
> +        <SampleSection text="Our Requests" />
adding onto Zora's idea about the props - you could make these divs using that same array of string titles too. that way we can limit hardcoded text as much as possible too.

2023-02-27 07:15 UTC, lizageorge commented on src/components/SecondaryNavBar.tsx
> +import type { FC } from 'react'
I don't think this is needed (unless you decide to pass in props to this component and make an interface for them)

2023-02-27 07:19 UTC, lizageorge commented
This is such a small thing, but I noticed this weird bug where the "UIS System" section isn't always correctly selected when clicked on. Instead the section right before it is highlighted, like the scrolling feature is off by a tiny amount. I can't figure out why this is happening to just this section, it very well might just be a quirk of react-scroll

https://user-images.githubusercontent.com/20449375/221498968-a778bb37-87f7-44f9-b876-ad8d3be2a02a.mov

But i really had to fight the thing to find this nit - otherwise incredibly smooth navbar 😎

2023-02-28 04:11 UTC, zorazrr approved these changes
Looks good, love the scroll animation!

2023-03-01 00:58 UTC, lizageorge commented on src/pages/home/index.tsx
> +      { path: 'ourRequests', text: 'Our Requests' },
Just a suggestion for the future - I think you could have kept this array in the info json file, and then refer to it in this component too (just mapping over it to actually init the divs and SampleSections below).

2023-03-01 01:04 UTC, lizageorge approved these changes
Looks good to me! Left a comment about the sample sections, but it's not worth a re-review, just a small thing :)

2023-03-01 01:04 UTC, lizageorge commented on src/pages/home/index.tsx
> +        <SampleSection text="" />
If these extra SampleSections were just for spacing while dev, it might be best to remove them before merging.

2023-03-01 01:05 UTC, zorazrr commented on src/pages/home/index.tsx
> +      { path: 'ourRequests', text: 'Our Requests' },
For this one, we could probably keep it in `home/index` because it is specific to that page. `home.json` is more so for text information.

2023-03-01 01:33 UTC, zorazrr commented on src/pages/home/index.tsx
> +        <SampleSection text="" />
These are kinda necessary for the last section to function, but potentially @eeshabarua we could make use of the `offset` property that comes with react-scroll to do some adjustments here. Check out this conversation here: https://github.com/fisshy/react-scroll/issues/335.

2023-03-02 23:11 UTC, merged