174 interactive treemap for fossil fuel page
toriis-portal/toriis pull request #178
Opened 2023-05-16 02:05 UTC by kennykos

## Summary

Description of PR here...
Closes #174

## Changes

- changed treemap on fossil fuel page from photo to dynamic apexchart

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/b29c159b-4265-4298-b9e2-922dbba462dc)

## TODO 

- [x] Create multidimensional tree chart that relies on DB queries
- [ ] Link to Fossil Fuel Page
- [x] Format each dimension as carbon underground 200 (red), fossil fuel (orange), and rest of the portfolio (blue)
- [ ] Display the company name on the chart and hover over amount of CO2, with the legend enabled
- [ ] On click, send to corresponding tare page
- [ ] Make sure it looks good in page

@zorazrr I would still like to check all these todo's before merging in, but I wanted to open a pr so we can discuss how it looks in page and getting the other technical stuff down. 

First and foremost, how can we get the dimensions right so that it is centered but only takes up say 75% of the width of the page. Also, how can we get the name to be cleaner that what is displayed? I thought we were going to overwrite the DB with company names from yahoo finance?

2023-05-16 04:08 UTC, zorazrr commented
1. You will need to wrap the `EmissionTreeMap` component in a div in `UniversityInvestments.tsx`, and adjust the wrapper div to be 75% and centered in the screen. 
2. We are. The ones that are not clean are not handled in the Python scripts and Yahoo Finance (either bc of ticker value or other stuff). Those cases I thought we are tackling those through the admin data update system, no?

2023-05-16 04:31 UTC, zorazrr commented on prisma/schema.prisma
> +  market_cap       Float?
Maybe rename this to `marketCap` for consistency.

2023-05-16 04:31 UTC, zorazrr commented on src/server/api/routers/company.ts
> +  getEmissionsAndFFClass: publicProcedure.query(async ({ ctx }) => {
I'm wondering if we could do this query with an [aggregation in Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing), or even a raw MongoDB query.

2023-05-16 04:33 UTC, zorazrr commented on src/server/api/routers/company.ts
> +  getEmissionsAndFFClass: publicProcedure.query(async ({ ctx }) => {
The graph looks so cool! Assuming this is still WIP, these comments only covered some high-level changes.

2023-05-16 04:33 UTC, zorazrr commented on prisma/schema.prisma
> +  market_cap       Float?
The graph looks so cool! Assuming this is still WIP, these comments only covered some high-level changes.

2023-05-16 13:13 UTC, kennykos commented
Here is what the treemap looks like in page now,
![image](https://github.com/toriis-portal/toriis/assets/73120774/8a6d0275-d06b-451c-8990-aad8b22f326e)

I think the dimensions are good for production, I like that the paragraph and the chart fit on page.

I still need to add legend and link to tare page.

2023-05-16 16:11 UTC, kennykos commented
Visually, the chart is where I want it to be

![image](https://github.com/toriis-portal/toriis/assets/73120774/5fd3b891-1a5a-48f2-abc4-2c91bd8d02c4)

:)

2023-05-30 06:27 UTC, zorazrr requested changes
The tree map looks really cool!

2023-05-30 06:27 UTC, zorazrr commented on src/components/Charts/EmissionTreeMap.tsx
> +    }
We can use `?` operator to do a pre-check. 
```suggestion
series[index]?.data.push(dataPoint)
```

2023-05-30 06:27 UTC, zorazrr commented on src/components/Charts/EmissionTreeMap.tsx
> +  for (const emission of emissionsAndFFClass) {
Can we write this into a helper function and apply it to the data we have? On first look, it might be confusing what this is doing so a descriptive function name might help!

2023-05-30 06:27 UTC, zorazrr commented on src/components/Charts/EmissionTreeMap.tsx
> +            series[config.seriesIndex].data[config.dataPointIndex]
This is possibly undefined, maybe use `?` operator as mentioned in another comment
```suggestion
          const selectedDataPoint =
            series[config.seriesIndex]?.data[config.dataPointIndex]
```

2023-05-30 06:27 UTC, zorazrr commented on src/server/api/routers/company.ts
> +            company.sector.toUpperCase().startsWith('UTILITIES'))
Because the company sector is defined to be an enum, it should be guaranteed to be in uppercase. Can make use of [SectorEnum defined here](https://github.com/toriis-portal/toriis/blob/8edaddf92482866e998efe8a14e2d9c58a208e10/src/utils/enums.ts#L1)!

2023-05-30 06:27 UTC, zorazrr commented on src/server/api/routers/company.ts
> +            company.sector.toUpperCase().startsWith('UTILITIES'))
A potential one-liner for defining `fossilFuelClass` would be awesome!

2023-05-30 06:27 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        netAssetVal &&
Nit. `netAssetVal` 100% exists here. 
```suggestion
```

2023-05-30 06:27 UTC, zorazrr requested changes
The tree map looks really cool!

2023-05-30 15:42 UTC, kennykos commented on src/components/Charts/EmissionTreeMap.tsx
> +  }[]
Updated in commit [adf08fbc06a2eca0c23410e3fbcf9bcaa9ceb4a0](https://github.com/kennykos/toriis/commit/adf08fbc06a2eca0c23410e3fbcf9bcaa9ceb4a0)

2023-05-30 15:46 UTC, kennykos commented on src/server/api/routers/company.ts
> +            company.sector.toUpperCase().startsWith('UTILITIES'))
> Because the company sector is defined to be an enum, it should be guaranteed to be in uppercase. Can make use of [SectorEnum defined here](https://github.com/toriis-portal/toriis/blob/8edaddf92482866e998efe8a14e2d9c58a208e10/src/utils/enums.ts#L1)!

So for this guy, I should have been using industry instead of sector. I noticed we don't have an industry enum, should I add this as well?

2023-05-30 16:19 UTC, kennykos commented on src/components/Charts/EmissionTreeMap.tsx
> +  for (const emission of emissionsAndFFClass) {
Added a helper function `formatSeries` in commit [2ceb37b165d9d33723de0270f904d80320443c76](https://github.com/kennykos/toriis/commit/2ceb37b165d9d33723de0270f904d80320443c76), hopefully this helps to clear things up :)

2023-05-31 01:49 UTC, zorazrr commented on src/server/api/routers/company.ts
> +            company.sector.toUpperCase().startsWith('UTILITIES'))
Oh yea then maybe we keep using string in this PR then. It would def be good to shift industry to enum in a separate issue/PR. (it is kinda addressed [here](https://github.com/toriis-portal/toriis/pull/173/files#diff-2ffd23c695e40b149649812baea03e6bd20e92e89918c59ee042a1e437925459))

2023-05-31 16:21 UTC, kennykos commented on src/server/api/routers/company.ts
> +            company.sector.toUpperCase().startsWith('UTILITIES'))
I merged in Daniel's code in commit [73380427b0cd2226f03dc261cef761f5d55a1f71](https://github.com/toriis-portal/toriis/pull/178/commits/73380427b0cd2226f03dc261cef761f5d55a1f71) and updated [src/server/api/routers/company.ts](https://github.com/toriis-portal/toriis/pull/178/files/678067f244e27ef3472d77fc7a936b52672128b3#diff-06b142de780b925e650129ceb963a0c834ddbdb0f7077f623c9a527d81de3f83) to use these enums in commit [8cc71c1a010693db82904d68f16169f6297fec48](https://github.com/toriis-portal/toriis/pull/178/commits/8cc71c1a010693db82904d68f16169f6297fec48)

2023-06-01 03:52 UTC, zorazrr requested changes
Some small NITs, but we could probably merge this soon!

2023-06-01 03:52 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          title={img.fields.title} // TODO: in contentful, change title to "Financed Emissions of University of Illinois System Investments"
Is there a reason for leaving this comment here? Since this change would be in Contentful, changing the code base for it seems unnecessary.

2023-06-01 03:52 UTC, zorazrr commented on src/components/Charts/EmissionTreeMap.tsx
> +    SourceData[] | null
Is this `null` necessary here?

2023-06-01 03:52 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        }
Nit. This looks kinda chunky. We can potentially define an array `FOSSIL_FUEL_INDUSTRIES` in the file `constants.ts` and do something like: 
```js
const fossilFuelClass = FOSSIL_FUEL_INDUSTRIES.includes(company.industry) ? 'y' : 'n'
```
Just a thought though. Also is `company.sector &&` still needed?

2023-06-01 15:11 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          title={img.fields.title} // TODO: in contentful, change title to "Financed Emissions of University of Illinois System Investments"
Completely unnecessary, good catch :)

2023-06-01 15:18 UTC, kennykos commented on src/components/Charts/EmissionTreeMap.tsx
> +    SourceData[] | null
Removed the `null` in commit [8893e8afe4e192d8605c86c641f039e07178d815](https://github.com/toriis-portal/toriis/pull/178/commits/8893e8afe4e192d8605c86c641f039e07178d815)

2023-06-01 15:35 UTC, kennykos commented on src/server/api/routers/company.ts
> +        }
See commit [876dac5e34434fae18cc2dbadd47a306eda65143](https://github.com/toriis-portal/toriis/pull/178/commits/876dac5e34434fae18cc2dbadd47a306eda65143)

2023-06-02 05:14 UTC, zorazrr commented on src/components/Charts/EmissionTreeMap.tsx
> +          window.open(url, '_blank')
Maybe use https://nextjs.org/docs/pages/api-reference/functions/use-router NextJs Router instead (`router.push`). A fixed URL doesn't really work for dev versus production.

2023-06-02 11:05 UTC, kennykos commented on src/components/Charts/EmissionTreeMap.tsx
> +          window.open(url, '_blank')
I got rid of `BASE_URL` and keeping the same window.open formatting, which works and avoids the same dev vs production issue in commit [03ab54deb4e143e4067ca350555eb5c16284efcf](https://github.com/toriis-portal/toriis/pull/178/commits/03ab54deb4e143e4067ca350555eb5c16284efcf). Is there any reason to use router.push over window.open, I could not figure out how to get router.push to open in a new tab.

2023-06-02 16:22 UTC, zorazrr approved these changes
lgtm!

2023-06-02 16:22 UTC, zorazrr approved these changes
lgtm!

2023-06-02 16:44 UTC, merged