Am/nav bar
toriis-portal/toriis pull request #18
Opened 2023-02-21 00:33 UTC by masgras2

## Summary

Closes #2 

## Changes

- Add styled nav button link components
- Add custom font and styles

## Screenshots

(Insert image, only for frontend)

2023-02-24 23:53 UTC, daniel-moon32 requested changes
Looks pretty good! A couple things to change here and there though

2023-02-24 23:53 UTC, daniel-moon32 commented on src/components/NavBar.tsx
> +            src={toriisimg}
I think the linter is throwing an error here because the img is not typed properly

2023-02-24 23:53 UTC, daniel-moon32 commented on src/components/NavBar.tsx
> +        <div className="flex" />
Nice use of flexbox!

2023-02-24 23:53 UTC, daniel-moon32 commented on src/components/NavButton.tsx
> +      <a
instead of the <a> html tag you should be using the nextjs Link component

2023-02-24 23:53 UTC, daniel-moon32 commented on src/pages/index.tsx
> +const Main = () => {
I'm not entirely sure why you removed the typing from the index page, but I think it should still be there (feel free to ignore me on this tho)

2023-02-24 23:53 UTC, daniel-moon32 commented on tailwind.config.cjs
> +      //Arial and Roboto are there to be other sans-serif
You don't need to add these comments. This is somewhat implied so it's not necessary to state this

2023-02-24 23:53 UTC, daniel-moon32 commented on src/components/NavButton.tsx
> +interface Nav {
I think you should rename this interface to something like NavButtonProps

2023-02-25 00:12 UTC, masgras2 commented on src/components/NavBar.tsx
> +            src={toriisimg}
For some reason the linter on my computer doesn't catch this, maybe I'm not searching the right things but I can't find this problem elsewhere. I've tried a couple things on previous git pushes but this keeps happening.

2023-02-25 00:50 UTC, zorazrr requested changes
Looks good overall! Just some small changes that need to be addressed. Additionally, let's move `src/img/toriis.png` to the `public` folder. 
Nice work!

2023-02-25 00:50 UTC, zorazrr commented on src/components/index.ts
> +export { NavBar }
Let's do `export {AuthButton , NavButton, NavBar}` here.

2023-02-25 00:50 UTC, zorazrr commented on src/components/NavButton.tsx
> +        <div className=" border-2 border-colbalt" />
```suggestion
        <div className=" border-2 border-cobalt" />
```

2023-02-25 00:50 UTC, zorazrr commented on src/components/NavButton.tsx
> +  const router = useRouter()
Nice use of `useRouter`!

2023-02-25 00:50 UTC, zorazrr commented on src/components/NavButton.tsx
> +      {router.pathname === link ? (
Instead of doing a separate `div` here, we can use conditional Tailwind classes with `clsx`, which will allow us to render border color based on condition here. Check out [this example](https://dev.to/joserfelix/6-tips-for-tailwind-css-development-with-resources-33i4#:~:text=No%20matter%20how%20many%20conditions%20there%20are%2C%20it%20is%20easier%20to%20read%20and%20keep%20track%20of.%20Let%27s%20look%20at%20the%20same%20above%20code%2C%20but%20in%20the%20new%20syntax%3A)!

2023-02-25 00:50 UTC, zorazrr commented on src/pages/index.tsx
> +    <div className="flex h-screen flex-col items-center justify-center bg-pumpkin">
```suggestion
    <div className="flex h-screen flex-col items-center justify-center">
```

2023-02-25 00:50 UTC, zorazrr commented on src/components/NavBar.tsx
> +            src={toriisimg}
Does something like `src={toriisimg as HTMLImageElement}` work?

2023-02-25 00:54 UTC, zorazrr commented on src/components/NavBar.tsx
> +            <NavButton title="Learn about Investments" link="/learn" />
```suggestion
            <NavButton title="Learn about Investments" link="/investments" />
```

2023-02-25 01:32 UTC, zorazrr commented on src/components/NavButton.tsx
> +      {router.pathname === link ? (
Also make sure font size is aligned with Figma.

2023-02-25 14:35 UTC, zorazrr requested changes
🚀 Some final nit changes and then we are good to merge!!

2023-02-25 14:35 UTC, zorazrr commented on src/components/NavBar.tsx
> +        <a href="link to main page" className="justify-start">
Let's use `<link>` here as well.

2023-02-25 14:35 UTC, zorazrr commented on src/components/NavBar.tsx
> +      <div className="flex flex-row items-center justify-between px-10">
Nit. Can these two two divs be merged into one? 
```
    <nav className="bg-white">
      <div className="flex flex-row items-center justify-between px-10">
```

2023-02-25 14:35 UTC, zorazrr commented on src/components/NavButton.tsx
> +          'border-cobalt': isActive,
Noice

2023-02-25 14:35 UTC, zorazrr commented on src/components/NavBar.tsx
> +            className=""
```suggestion
```

2023-02-25 14:35 UTC, zorazrr commented on src/components/NavBar.tsx
> +            width="100"
Nit. Let's not hard code image width and height. Something like `h-full w-auto` would be ideal. We can fix the nav bar height instead.

2023-02-25 18:23 UTC, zorazrr approved these changes

2023-02-25 18:25 UTC, daniel-moon32 approved these changes
Nice work!

2023-02-25 18:34 UTC, merged