Treemap experimentation
toriis-portal/toriis pull request #180
Opened 2023-06-11 21:40 UTC by kennykos

## Summary

Description of PR here...
Closes #179 

## Changes

- Added buttons to toggle between financed emission and net asset value treechart

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/21aef6fd-4996-49bd-a578-29e363c36560)

## TODO:

- [ ] Have left button stack on top of right button shadow (@zorazrr any advice on this is greatly appreciated)
- [ ] Add discription for the difference between the two treecharts (waiting for @faithlos on the figma)
- [ ] Make the title names cleaner (right now they are ugly and too technical) 
- [ ] Check with design professional on dimensions of the chart (@faithlos)
- [ ] Check with design professional on size of company title       (@faithlos)
- [ ] Clicking a sector zooms into a treemap of sector                    (@faithlos can we get a design so this is clickable?)
- [ ] Hovering over sector name triggers toottip that gives the percentage breakdown of the given sector

2023-06-12 21:14 UTC, kennykos commented
@zorazrr the previous commit has it take up the correct portion of my screen for the given aspect ratio, how can I make it aspect ratio agnostic
?

2023-06-13 21:53 UTC, kennykos commented
With the most recent commit, I sometimes get a hydration error

![image](https://github.com/toriis-portal/toriis/assets/73120774/86c60411-4b27-4796-a060-8f8925d2a85b)


I don't know why :(

2023-06-14 18:00 UTC, kennykos commented
I think the solution to the shadow overlapping is here [https://www.w3.org/TR/CSS2/visuren.html#z-index](https://www.w3.org/TR/CSS2/visuren.html#z-index), but I'm struggling with the code implementation.

2023-06-15 15:28 UTC, kennykos commented
> 

The hydration error seems to be caused by using the ToolTip inside the PrimaryButton

2023-06-15 17:09 UTC, kennykos commented
> > 
> 
> The hydration error seems to be caused by using the ToolTip inside the PrimaryButton

I fixed this by unnesting the button and the tooltip

2023-06-16 03:47 UTC, zorazrr requested changes
Sorry for the late review!

2023-06-16 03:47 UTC, zorazrr commented on src/server/api/routers/company.ts
> -            : 'n'
Looking back at this procedure, it will probably be cleaner if we filter out empty values first and then do the `map`. Take it with a grain of salt though.

2023-06-16 03:47 UTC, zorazrr commented on src/components/chart/EmissionTreeMap.tsx
>        fossilFuelClass: 'y',
Looking back here probably should name `'y'` to be a bit more descriptive.

2023-06-16 03:47 UTC, zorazrr commented on src/components/chart/EmissionTreeMap.tsx
> +      name: sectorEnum.BASIC_MATERIALS,
Maybe something like this: 
```ts
  ...Object.values(sectorEnum)
    .filter((sector) => {
      sector != sectorEnum.UTILITIES && sector != sectorEnum.ENERGY
    })
    .map((sector) => ({
      fossilFuelClass: sector,
      name: sector,
      data: [],
    })),
```

2023-06-16 03:47 UTC, zorazrr commented on src/components/chart/EmissionTreeMap.tsx
>    for (const emission of data) {
Looking back here, could probably do a more functional style programming to`filter` out `null` values and then do a `forEach`. This is Nit though.

2023-06-16 16:32 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +        <div className="flex flex-col md:flex-row">
Do you have a visual of what TabButton or Tabs looks like when implemented?

2023-06-17 00:03 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +        <div className="flex flex-col md:flex-row">
TabButtons are from admin control pages: https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?type=design&node-id=2653-2711&t=6XKXZwi8pKW4rXTJ-0. Tabs is the one on Fossil Fuel Page https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?type=design&node-id=2653-2711&t=6XKXZwi8pKW4rXTJ-0.

2023-06-17 12:29 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +        <div className="flex flex-col md:flex-row">
Ok, I think this is something @faithlos should chime in on, but so far the 3 options are

- Custom Toggle 
![image](https://github.com/toriis-portal/toriis/assets/73120774/7e56c3d9-e550-471e-903c-4c21e78a129f)

- Tab Buttons 
![image](https://github.com/toriis-portal/toriis/assets/73120774/bf435bfc-42f6-4697-82c3-a957b568f506)

- Tabs
![image](https://github.com/toriis-portal/toriis/assets/73120774/af3a0018-d290-4e01-8e78-4713202c739a)


I think if we go with custom toggle I should make it into an actual component

2023-06-17 13:26 UTC, kennykos commented on src/components/button/PrimaryButton.tsx
> +  toolTip,
addressed in commit [9acb6634125fb83bc456450cded7dfc33b6a1c43](https://github.com/toriis-portal/toriis/pull/180/commits/9acb6634125fb83bc456450cded7dfc33b6a1c43)

2023-06-17 13:33 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +            style={{ zIndex: 1, position: 'relative' }}
no reason, addressed in commit [a61b5c8d2fe736381b135dfc46beb8a56a6e5f83](https://github.com/toriis-portal/toriis/pull/180/commits/a61b5c8d2fe736381b135dfc46beb8a56a6e5f83)

2023-06-19 16:16 UTC, kennykos commented on src/components/chart/EmissionTreeMap.tsx
>        fossilFuelClass: 'y',
Addressed in commit [f2e783e6a020c0b06f250d98e1533805cce0aee7](https://github.com/toriis-portal/toriis/pull/180/commits/f2e783e6a020c0b06f250d98e1533805cce0aee7)

2023-06-19 17:03 UTC, faithlos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +        <div className="flex flex-col md:flex-row">
I will do some mock-ups of the TabButtons with the treemap by Friday!

2023-06-19 17:18 UTC, kennykos commented on src/components/chart/EmissionTreeMap.tsx
>    for (const emission of data) {
Right now I have it as 
```
  const series: FossilFuelSeries[] = [
    {
      fossilFuelClass: 'Fossil Fuel Companies',
      name: 'Fossil Fuel Companies',
      data: [],
    },
    ...Object.values(sectorEnum)
      .filter(
        (sector) => ![sectorEnum.UTILITIES, sectorEnum.ENERGY].includes(sector),
      )
      .map((sector) => ({
        fossilFuelClass: sector,
        name: sector,
        data: [],
      })),
  ]
``` 
What would be the benefits to a functional style?

2023-06-19 18:11 UTC, kennykos commented on src/server/api/routers/company.ts
> -            : 'n'
So I'm trying to put in a filter, do you know just by a glance why this code is not working

```
    const emissionsAndFFClass = companies
    .filter(company => (
      company.marketCap !== null &&
      company.emission?.scopeOne !== null &&
      company.emission?.scopeTwo !== null &&
      company.industry !== null
    ))
    .map((company) => {
      const netAssetVal = company.netAssetVal
      const marketCap = company.marketCap
      const emissionInfo = company.emission

        const financedEmissions =
          (netAssetVal / marketCap) *
          (emissionInfo.scopeOne + emissionInfo.scopeTwo) *
          1000

        const fossilFuelClass =
          company.industry !== null &&
          FOSSIL_FUEL_INDUSTRIES.includes(company.industry)
            ? 'Fossil Fuel Companies'
            : company.sector
            ? sectorEnum[company.sector]
            : 'N/A'

        return {
          companyName: company.name,
          companyId: company.id,
          financedEmissions,
          netAssetVal,
          fossilFuelClass,
        }
    })
    ```

2023-06-20 05:11 UTC, zorazrr commented on src/components/chart/EmissionTreeMap.tsx
>    for (const emission of data) {
Several benefits for using higher-order functions:  
- Better maintainability and readability as it gives a clearer declaration of the starting state and intermediate steps
- Does not require side-effects or mutable states (not sure if this is the right word here lol, but referring to stuff like `yVal` and `pushBack` to an empty array
- In general it's more javascript-y 
I guess it's partially personal choices, but maintainability and readability is a large part.

2023-06-20 05:37 UTC, zorazrr commented on src/server/api/routers/company.ts
> -            : 'n'
Huh this looks all good to me. What is the error?

2023-06-21 17:00 UTC, kennykos commented
> Vercel had trouble deploying `EmissionTreeMap`:
> 
> ```
> Type error: Argument of type '({ companyName: string; companyId: string; financedEmissions: number; netAssetVal: number; fossilFuelClass: string; } | undefined)[]' is not assignable to parameter of type '(SourceData | null)[]'.
> ```
> 
> There is also merge conflict.

The vercel error should be fixed by commit [5c17c427828f108dfdd70e637d84b6bd6aa1bcea](https://github.com/toriis-portal/toriis/pull/180/commits/5c17c427828f108dfdd70e637d84b6bd6aa1bcea), and the merge conflict is resolved in commit [e746b4aca1d4f3ab65e57d7d94a61c808bf23466](https://github.com/toriis-portal/toriis/pull/180/commits/e746b4aca1d4f3ab65e57d7d94a61c808bf23466)

2023-06-21 17:01 UTC, kennykos commented
Just a remind to switch the dev db over to the prod db as I made some changes.

2023-06-21 17:34 UTC, kennykos commented
> Just a remind to switch the dev db over to the prod db as I made some changes.

Wait sorry please **DO NOT** merge in the dev db to prod db. I need to reset it.

2023-06-22 03:08 UTC, zorazrr commented
One more deployment error -- this is in `fossil-fuel/index.tsx`. 

```
Type error: Type '{ img: Asset; caption: Document; }' is not assignable to type 'IntrinsicAttributes & UniversityInvestmentsProps'.
--
Property 'img' does not exist on type 'IntrinsicAttributes & UniversityInvestmentsProps'.
```
In the future if you branch directly off of the toriis repo, the Vercel workflow will be able to go through and highlight the errors.

2023-06-22 03:57 UTC, zorazrr commented on src/server/api/routers/company.ts
> -            : 'n'
Ah okay TypeScript is not picking up on the filter. Nevermind then, my bad.

2023-06-22 10:29 UTC, kennykos commented
> One more deployment error -- this is in `fossil-fuel/index.tsx`.
> 
> ```
> Type error: Type '{ img: Asset; caption: Document; }' is not assignable to type 'IntrinsicAttributes & UniversityInvestmentsProps'.
> --
> Property 'img' does not exist on type 'IntrinsicAttributes & UniversityInvestmentsProps'.
> ```
> 
> In the future if you branch directly off of the toriis repo, the Vercel workflow will be able to go through and highlight the errors.

Commit [7bbf35e7f0944b4a6af9e4ece07609362932e1dd](https://github.com/toriis-portal/toriis/pull/180/commits/7bbf35e7f0944b4a6af9e4ece07609362932e1dd) should fix this.

p.s. I will branch off toriis from now on :vulcan_salute:

2023-06-23 03:50 UTC, zorazrr reviewed
Some small css stuff lingering, other than that probably good to merge!

2023-06-23 03:50 UTC, zorazrr commented on src/components/button/PrimaryButton.tsx
> +            </div>
If we add `flex flex-row items-center` to `buttonStyle` defined above, we don't need this extra div here. 

```suggestion
              {text}
              {children}
```

2023-06-23 03:50 UTC, zorazrr commented on src/components/button/PrimaryButton.tsx
> +          </div>
```suggestion
            {text}
            {children}
```
Same as above^

2023-06-23 03:50 UTC, zorazrr commented on src/components/button/PrimaryButton.tsx
> +            </div>
Oh I realized this causes the button in `InvestmentTable` to be misaligned, but it's probably better to change the div that wraps that button instead of adding two layers of div here?

2023-06-23 03:50 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +                  'Greenhouse gas (GHG) emissions indirectly caused by financial activities, investments, or lending practices of individuals, organizations, or institutions that support projects or
Note to self to address this in a separate PR, should probably put all Tooltip content into `constants.ts`.

2023-06-23 03:50 UTC, zorazrr commented on src/components/button/PrimaryButton.tsx
> +            </div>
And a reminder to use Tailwind ~

2023-06-26 13:56 UTC, kennykos commented on src/components/button/PrimaryButton.tsx
> +            </div>
Addressed this in commit [https://github.com/toriis-portal/toriis/pull/180/commits/942224cfc57212cc7532959ecda461dc827101da](942224cfc57212cc7532959ecda461dc827101da), I'm not sure what you mean by 
> Oh I realized this causes the button in `InvestmentTable` to be misaligned, but it's probably better to change the div that wraps that button instead of adding two layers of div here?

2023-06-26 14:03 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +                  'Greenhouse gas (GHG) emissions indirectly caused by financial activities, investments, or lending practices of individuals, organizations, or institutions that support projects or
opened issue #183

2023-06-27 01:13 UTC, zorazrr approved these changes
LGTM

2023-06-27 01:17 UTC, merged