Gk/182 switch to richtext for schools and institutions divested lists
toriis-portal/toriis pull request #184
Opened 2023-06-26 20:25 UTC by kennykos

## Summary

Closes #182 

This PR only addresses backend, so no visual updates on the site.

## Changes

- Switched type from string to Document for `fossilFuelPageEntries` where contentful switched from markdown to richText
- `parseEntryToColumns` to handle richtext documents
- added custom parser `parseHREFStringToHTML` for contentful html strings separated by a newline
- Turned footnotes into clickable links from contentful

- [ ] **AFTER CODE REVIEW AND BEFORE MERGE, REMOVE `New` FROM CONTENTFUL FIELDS, DELETE THE OLD FIELDS, AND UPDATE THE  CODE ACCORDINGLY**

2023-06-27 19:49 UTC, faithlos commented
<img width="1452" alt="image" src="https://github.com/toriis-portal/toriis/assets/71426784/4808a386-dd57-4162-afd0-9236e8a5e80e">

it would be nice if the links looked clickable similar to the underline + arrows in this text 

<img width="1340" alt="image" src="https://github.com/toriis-portal/toriis/assets/71426784/0a9c9b7e-1523-4d9d-8e79-5baa69dbf731">

2023-06-27 20:19 UTC, kennykos commented
> <img alt="image" width="1452" src="https://user-images.githubusercontent.com/71426784/249267341-4808a386-dd57-4162-afd0-9236e8a5e80e.png">
> it would be nice if the links looked clickable similar to the underline + arrows in this text
> 
> <img alt="image" width="1340" src="https://user-images.githubusercontent.com/71426784/249267694-0a9c9b7e-1523-4d9d-8e79-5baa69dbf731.png">

addressed in commit [843ad3e2e3970b07d6e5c75c8c8ba6459e09c779](https://github.com/toriis-portal/toriis/pull/184/commits/843ad3e2e3970b07d6e5c75c8c8ba6459e09c779)

2023-06-29 03:59 UTC, daniel-moon32 requested changes
Couple small things, but otherwise looks good!

2023-06-29 03:59 UTC, daniel-moon32 commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> + * Parse a string of the type "<a href="https://www.insidehighered.com/quicktakes/2020/04/22/american-u-divests-fossil-fuels">American University</a>"" to HTML
Could you explain the purpose of this? I think I'm not entirely understanding

2023-06-29 03:59 UTC, daniel-moon32 commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> +  const list = entry.slice(3, -4).split('\n')
Slicing by (3, -4) is somewhat unclear on what the purpose is (Either remove the magic numbers or add a comment)

2023-06-29 03:59 UTC, daniel-moon32 commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> + * Parse a string of the type "<a href="https://www.insidehighered.com/quicktakes/2020/04/22/american-u-divests-fossil-fuels">American University</a>"" to HTML
I realized you explained this on the PR, but I think it'll be good for maintainability to make a note here as well

2023-06-29 03:59 UTC, daniel-moon32 commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> +  const list = str.split('"')
Nit. List is not a poor variable name

2023-06-29 14:05 UTC, kennykos commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> + * Parse a string of the type "<a href="https://www.insidehighered.com/quicktakes/2020/04/22/american-u-divests-fossil-fuels">American University</a>"" to HTML
updated the comment for this function
```javascript
/**
 * Purpose: Parse a string of the type "<a href="https://www.insidehighered.com/quicktakes/2020/04/22/american-u-divests-fossil-fuels">American University</a>"" to
 *          <Link> ... </Link> HTML class
 *
 * Rationale: When switching over to contentful richtext, we want to maintain the general functionality of the `parseEntryToColumns` function (i.e. take in a text
 *            list from contentful, and create "array of React nodes for Carousel"). To do this, we get our string of divested entries by calling the contentful
 *            function `documentToHtmlString()`, which returns a string of consecutive <a> ... </a> HTML classes wrapped inside a <p> </p> HTML class. We then unwrap the
 *            <p> ... </p> class and turn the string of consecutive <a> ... </a> into a list to be parsed (see `const list = entry.slice(3, -4).split('\n')`).
 *            Thus, this function is needed to parse the contentful richtext into the correct <Link> ... </Link> HTML class to be displayed.
 *
 * @param str string of the type <a href="https://www.insidehighered.com/quicktakes/2020/04/22/american-u-divests-fossil-fuels">American University</a>
 * @returns HTML to be rendered
 */
```

In commit [70aa523dc7c9352d121605311357982fd9ca4a29](https://github.com/toriis-portal/toriis/pull/184/commits/70aa523dc7c9352d121605311357982fd9ca4a29)

2023-06-29 14:06 UTC, kennykos commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> +  const list = entry.slice(3, -4).split('\n')
Updated comment

```javascript
  /*
   * Segment string by new line. We slice by (3, -4) because the documentToHtmlString function from contentful wraps <a> ... </a> classes,
   * which we want, in a <p> </p> class, which we do not want. So we cut out <p> (3 characters) from the front and </p> (4 characters) from the back.
   */
   ```
   
In commit [70aa523dc7c9352d121605311357982fd9ca4a29](https://github.com/toriis-portal/toriis/pull/184/commits/70aa523dc7c9352d121605311357982fd9ca4a29)

2023-06-29 14:08 UTC, kennykos commented on src/sections/fossil-fuel/SchoolsDivested.tsx
> +  const list = str.split('"')
addressed in commit [1edd35010a657ec8844c732cbe8aaadcc2c8c458](https://github.com/toriis-portal/toriis/pull/184/commits/1edd35010a657ec8844c732cbe8aaadcc2c8c458)

2023-06-29 18:24 UTC, daniel-moon32 approved these changes
Looks good!

2023-06-29 18:26 UTC, merged