Take action page bare bones
toriis-portal/toriis pull request #211
Opened 2023-07-17 06:08 UTC by lizageorge

## Summary

Closes #191 

## Changes

- Created take-action page
- Added navbars
- Added sections with headers
- Created Contentful model for open letter, imported to OpenLetter section

## Screenshots
<img width="1259" alt="image" src="https://github.com/toriis-portal/toriis/assets/20449375/33b2bdcb-ed99-47a9-8728-f9ca8fe87737">
<img width="1257" alt="image" src="https://github.com/toriis-portal/toriis/assets/20449375/a797bb28-00de-4073-b528-a83c0c6dade3">

2023-07-17 14:08 UTC, kennykos commented on src/components/navigation/PrimaryNavBar.tsx
> +          <NavButton title="Take Action" link="/open-letter" />
When I click on the nav-bar I get directed to `http://localhost:3000/open-letter` (which is good) but the page gives a `404` error.

![image](https://github.com/toriis-portal/toriis/assets/73120774/70ca69ce-7fec-4b66-b32d-309c7cee3d63)

We should be routing to `take-action`

2023-07-24 13:13 UTC, kennykos approved these changes
Looks good to me! Great Job :smile:

2023-07-24 13:34 UTC, kennykos requested changes
One small change, but otherwise this looks very good to me!

2023-07-24 13:34 UTC, kennykos commented on src/sections/take-action/letter.tsx
> +      <div className="space-y-4 px-60">
I know this wasn't in the Figma and Issue, but looking at the page, the text seems to be too wide.
![image](https://github.com/toriis-portal/toriis/assets/73120774/5a6c51a6-fe82-4733-a65f-0af6eb72bd95)

We should be aiming for text of more paper width, like so 
![image](https://github.com/toriis-portal/toriis/assets/73120774/7ff6ce1e-1f1c-4870-80d7-00dd74d3226d)
https://fossilfreeresearch.org/letter/

2023-07-24 20:28 UTC, kennykos commented on src/sections/take-action/letter.tsx
> +      <div className="space-y-4 px-60">
```suggestion
      <div className="space-y-6 w-2/4">
```

This spacing should do the trick, after that it should be good to go!

2023-07-24 20:29 UTC, kennykos requested changes
Ok, with this spacing changes this commit should be good to go and ready to merge.

2023-07-27 07:18 UTC, lizageorge commented on src/sections/take-action/letter.tsx
> +      <div className="space-y-4 px-60">
ok, updated this! but it's kind of a temporary fix, we should 100% create a more mobile-friendly option before quad day.

2023-07-27 12:05 UTC, kennykos approved these changes
Looks good to me!

2023-08-01 00:11 UTC, merged