Change Treemap Toggles & Rename fossil fuel page to why divest
toriis-portal/toriis pull request #213
Opened 2023-07-27 18:01 UTC by kennykos

## Summary

Closes #207 

## Changes

- Create Underlined Title Component
- Update Treemap Toggles
- Update Why Divest? page title 

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/af436968-8d4d-47fc-b732-c3d4a06bab5a)
![image](https://github.com/toriis-portal/toriis/assets/73120774/dbd08e8d-ccdc-49bc-aa33-7fdf2edea756)

2023-08-18 00:33 UTC, zorazrr requested changes
Some CSS

2023-08-18 00:33 UTC, zorazrr commented on src/components/text/UnderlinedTitle.tsx
> +        />
Not sure if using a div is intentional, but we could use `text-decoration: underline` directly.

2023-08-18 00:33 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +              </Toggle>
Nit, idk if the width of the two toggles should be aligned? 
<img width="338" alt="image" src="https://github.com/toriis-portal/toriis/assets/61670566/3fb19d62-b5e5-48b2-8a14-64868df4e63d">

2023-08-18 00:33 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +                }
Wrapping the component in `{}` is probably not necessary here.

2023-08-18 00:33 UTC, zorazrr commented on src/components/toggle/Toggle.tsx
> +const Toggle: FC<ToggleProps> = ({
Bc of the style overlaps maybe it'd be good to modify and generalize the existing `TabButton` component rather than making a new one.

2023-08-18 00:33 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +              </Toggle>
Another UI nit, would it make more sense to put the tooltip info outside of this tab button? Considering that it would align better with other parts of the website, and that this button is kinda narrow.

2023-08-18 00:33 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +            </div>
```suggestion
            <div className="w-full">
              <EmissionTreeMap flag={flag} />
            </div>
```
Seems like some `div`s in this file can be merged together, can we check to make sure we are keeping `div` layers clean?

2023-08-18 00:55 UTC, kennykos commented on src/components/text/UnderlinedTitle.tsx
> +        />
I'm confused, don't we need the custom code here to get the distinct orange underline we want?

2023-08-18 01:09 UTC, zorazrr commented on src/components/text/UnderlinedTitle.tsx
> +        />
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color

2023-08-18 01:10 UTC, kennykos commented on src/components/text/UnderlinedTitle.tsx
> +        />
wait nevermind I got it [https://tailwindcss.com/docs/text-decoration-color](https://tailwindcss.com/docs/text-decoration-color)

2023-08-18 01:29 UTC, kennykos commented on src/components/text/UnderlinedTitle.tsx
> +        />
ok I removed the Underlined Titles class

2023-08-18 01:39 UTC, kennykos commented on src/components/toggle/Toggle.tsx
> +const Toggle: FC<ToggleProps> = ({
where is the TabButton used so I can have a reference?

2023-08-18 02:07 UTC, kennykos commented on src/components/toggle/Toggle.tsx
> +const Toggle: FC<ToggleProps> = ({
I switched to tab buttons, but for the life of me I cant get the spacing right. Do you have any advise?

2023-08-18 03:29 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +  const TabButtonGroupStyle = clsx('flex flex-row gap-2 basis-1/2 items-center')
```suggestion
  const TabButtonGroupStyle = clsx('flex flex-row gap-2 items-center')
```

2023-08-18 13:50 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +  const TabButtonGroupStyle = clsx('flex flex-row gap-2 basis-1/2 items-center')
wait I still have the spacing issues even with this on my screen

2023-08-18 13:50 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +  const TabButtonGroupStyle = clsx('flex flex-row gap-2 basis-1/2 items-center')
![image](https://github.com/toriis-portal/toriis/assets/73120774/e88bf13d-48a1-4d44-aac3-957e33f2c040)

2023-08-18 14:44 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +  const TabButtonGroupStyle = clsx('flex flex-row gap-2 basis-1/2 items-center')
Ok I finally got it, jeez that took a while

2023-08-19 20:46 UTC, zorazrr requested changes
Some final changes

2023-08-19 20:46 UTC, zorazrr commented on src/pages/investments/index.tsx
> +              <a className="underline decoration-clementine decoration-8">
Should make this into a component so that we can re-use this styling.

2023-08-19 20:46 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="w-full md:px-10 lg:px-20 xl:px-40 2xl:px-80">
These two `div`s can be merged I believe.

2023-08-19 20:47 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="w-full md:px-10 lg:px-20 xl:px-40 2xl:px-80">
Also would be good to check for any other merge-able divs.

2023-08-19 20:58 UTC, kennykos commented on src/pages/investments/index.tsx
> +              <a className="underline decoration-clementine decoration-8">
What if I made the styling into constants. The thing about a component is that the underline can come at any part of the title, which would make the component needlessly complicated. For instance the title: Investments **2022** vs **6000** metric tons of carbon (bold instead of underlined but you get the point)

2023-08-19 21:03 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="w-full md:px-10 lg:px-20 xl:px-40 2xl:px-80">
these guys can not be merged 
![image](https://github.com/toriis-portal/toriis/assets/73120774/aa105b08-556f-40eb-a1a3-c7f019911341)

2023-08-19 21:06 UTC, zorazrr commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="w-full md:px-10 lg:px-20 xl:px-40 2xl:px-80">
Adding a `flex-col` should do it, `flex justify-center` doesn't really do anything here.

2023-08-19 21:44 UTC, zorazrr commented on src/utils/constants.ts
> +  UNDERLINE: 'underline decoration-clementine decoration-8',
Just kidding! Maybe adding it to `global.css` is the best move.

2023-08-19 21:54 UTC, kennykos commented on src/utils/constants.ts
> +  UNDERLINE: 'underline decoration-clementine decoration-8',
Done!

2023-08-19 23:32 UTC, zorazrr approved these changes
lgtm!

2023-08-20 02:50 UTC, merged