Signatories Carousal
toriis-portal/toriis pull request #214
Opened 2023-08-06 03:01 UTC by kennykos

## Summary

Add Signatories Carousal to the Take Action Page
Closes #193 

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/7b06aa79-7b55-419f-af22-2f6179775b9e)

2023-08-14 07:23 UTC, lizageorge requested changes

2023-08-14 07:23 UTC, lizageorge commented on src/sections/take-action/signatories.tsx
> +  const grid = `p-12 grid w-full grid-cols-${numCols}`
The side padding on the Figma was greater than this, something like `p-16` might be a better fit (especially considering that we probably won't have a lot of completed fields.

2023-08-14 07:23 UTC, lizageorge commented on src/sections/take-action/signatories.tsx
> +  const grid = `p-12 grid w-full grid-cols-${numCols}`
Also, was there a reason to make this a separate variable? leaving the styles in the component's className, like tailwind's default practices, might be more readable.

2023-08-14 07:23 UTC, lizageorge commented on src/sections/take-action/signatories.tsx
> +  entryType: 'text' | 'html',
This parameter seems to be unused

2023-08-14 07:23 UTC, lizageorge commented on src/server/api/routers/signatory.ts
> +      orderBy: { createdAt: 'desc' },
Possible idea, we can discuss this more live - should we also order these results by which entries have more non-empty fields?

2023-08-14 14:29 UTC, kennykos commented on src/sections/take-action/signatories.tsx
> +  const grid = `p-12 grid w-full grid-cols-${numCols}`
Addressed in commit [abb18cf49f1f7f166f2977fd4ada6dc1e3891541](https://github.com/toriis-portal/toriis/pull/214/commits/abb18cf49f1f7f166f2977fd4ada6dc1e3891541)

2023-08-14 14:29 UTC, kennykos commented on src/sections/take-action/signatories.tsx
> +  const grid = `p-12 grid w-full grid-cols-${numCols}`
No reason, also addressed in commit [abb18cf49f1f7f166f2977fd4ada6dc1e3891541](https://github.com/toriis-portal/toriis/pull/214/commits/abb18cf49f1f7f166f2977fd4ada6dc1e3891541)

2023-08-14 14:29 UTC, kennykos commented on src/sections/take-action/signatories.tsx
> +  entryType: 'text' | 'html',
Deleted in commit [abb18cf49f1f7f166f2977fd4ada6dc1e3891541](https://github.com/toriis-portal/toriis/pull/214/commits/abb18cf49f1f7f166f2977fd4ada6dc1e3891541)

2023-08-14 14:30 UTC, kennykos commented on src/server/api/routers/signatory.ts
> +      orderBy: { createdAt: 'desc' },
Yes, let's discuss tonight!

2023-08-18 01:24 UTC, zorazrr requested changes
Nits.

2023-08-18 01:24 UTC, zorazrr commented on src/sections/take-action/signatories.tsx
> +                    : ' '}
Maybe make these into helper functions and reuse.

2023-08-18 01:24 UTC, zorazrr commented on src/sections/take-action/signatories.tsx
> +}
This is equivalent to the `Signatory` type imported from `@prisma/client` right?

2023-08-18 01:24 UTC, zorazrr commented on src/sections/take-action/signatories.tsx
> +  const { data } = api.signatory.getSignatories.useQuery<Signatory[]>(
Unrelated to this PR, but once we have a lot of signatories, having some pagination in this query would be good.

2023-08-18 01:24 UTC, zorazrr commented on src/sections/take-action/signatories.tsx
> +      />
Unrelated to this PR, just want to confirm that we don't want the footer on the take actions page?

2023-08-18 02:27 UTC, kennykos commented on src/sections/take-action/signatories.tsx
> +      />
we do, I just pushed it, great catch

2023-08-18 03:00 UTC, zorazrr commented on src/sections/take-action/signatories.tsx
> +}
In that case we could directly use `Signatory` type rather than declaring a duplicate interface.

2023-08-18 03:04 UTC, kennykos commented on src/sections/take-action/signatories.tsx
> +}
Yep, just did that, thanks for pointing that out

2023-08-18 03:08 UTC, zorazrr approved these changes
LGTM!

2023-08-18 03:23 UTC, merged