Implement Continue the Momentum Section
toriis-portal/toriis pull request #217
Opened 2023-08-08 13:42 UTC by kennykos

## Summary

Closes #215 

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/02c7e199-2968-49a5-a83a-f0aab710c5d5)

2023-08-14 07:37 UTC, lizageorge submitted a review, later dismissed

2023-08-14 07:37 UTC, lizageorge commented on src/sections/take-action/momentum.tsx
> +    <div className="px-12">
The page needs some whitespace on the bottom, i'd recommend adding a `pb-36` here. Also the side padding is less than that on the figma, maybe use `px-16` instead.

2023-08-14 07:37 UTC, lizageorge commented on src/sections/take-action/momentum.tsx
> +      <div className="my-6 w-full md:px-12">
There needs to be signaficantly more white space between header and list, maybe `mt-16` instead.

2023-08-14 07:37 UTC, lizageorge commented on src/utils/content.ts
> +      case 'continueTheMomentumEntries':
More so a comment on the Contentful content - the Figma had all the list items ending in a comma, except the last one which ends in an exclamation point.

2023-08-14 14:38 UTC, kennykos commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] space-y-6">
Addressed in commit [de0cd59bc80c5899054ab2a53d186dbf1c4476cf](https://github.com/toriis-portal/toriis/pull/217/commits/de0cd59bc80c5899054ab2a53d186dbf1c4476cf)

2023-08-14 14:41 UTC, kennykos commented on src/utils/content.ts
> +      case 'continueTheMomentumEntries':
Changed via contentful!

2023-08-16 00:02 UTC, zorazrr requested changes

2023-08-16 00:02 UTC, zorazrr commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
For mobile responsiveness maybe add some media breakpoints here.

2023-08-16 00:33 UTC, kennykos commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
It seem's to be pretty responsive just with the `md:px-12` already hear (also, I took this formatting from the Institutional Divestment section on the Home page)
Here is what the mobile view looks like for me
![image](https://github.com/toriis-portal/toriis/assets/73120774/f05b75a8-599a-4a1e-973d-a6d002579850)

2023-08-16 00:38 UTC, zorazrr commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
on iPhone XR it's kinda squeezed together
<img width="525" alt="image" src="https://github.com/toriis-portal/toriis/assets/61670566/5f399636-a441-4744-b7c3-c809607958ce">

2023-08-16 00:45 UTC, kennykos commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
That's so odd, on my version of iPhone XR it looks fine
![image](https://github.com/toriis-portal/toriis/assets/73120774/d292ddc9-d9e2-47e8-ba29-122b088517c2)

2023-08-16 00:46 UTC, kennykos commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
Wait sorry I forgot to push my commit :hand_over_mouth:

2023-08-16 00:49 UTC, kennykos commented on src/sections/take-action/momentum.tsx
> +        <div className="ml-[3%] w-4/6 space-y-6">
ok should be good now

2023-08-16 01:45 UTC, zorazrr approved these changes
lgtm

2023-08-16 01:48 UTC, merged