Xl primarybutton
toriis-portal/toriis pull request #22
Opened 2023-02-23 23:33 UTC by 21xiaofanli

## Summary

Description of PR here...
Closes #85, Closes #22

## Changes

- created primary button for learn more about investments and fossil fuel

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-02-24 05:58 UTC, zorazrr requested changes
The button is looking good! Just need to address some small fixes. Additionally, `package-lock.json` should not be here as we are using yarn not npm.

2023-02-24 05:58 UTC, zorazrr commented on src/components/PrimaryButton.tsx
> +const PrimaryButton: React.FC<{ text: string; link: string }> = ({
We can extract what is in `FC<{text:string; link: string}>` into an interface 
```
buttonProps {
   text: string,
   link: string
}
```

2023-02-24 05:58 UTC, zorazrr commented on src/components/PrimaryButton.tsx
> +          {text} <ArrowRightIcon className="bold inline h-9 w-5" />{' '}
```suggestion
          {text} <ArrowRightIcon className="bold inline h-9 w-5" />
```

2023-02-24 06:59 UTC, zorazrr commented on src/components/PrimaryButton.tsx
> +      <button className="rounded border-2 border-solid border-cobalt bg-lightBlue px-5 py-1 shadow-[-8px_8px_0px_0px] shadow-cobalt hover:shadow-[-5px_5px_0px_0px] hover:shadow-cobalt ">
This line is super long. I added a new package `cslx` that will help with this specific situation with Tailwind CSS. An example usage can be found [here](https://dev.to/joserfelix/6-tips-for-tailwind-css-development-with-resources-33i4#:~:text=My%20solution%20to%20this%20type%20of%20long%20class%20names%20is%20using%20comma%2Dseparated%20values%20in%20clsx.%20Like%20this%3A)! So merge main and try it out!

2023-02-25 08:07 UTC, 21xiaofanli commented
Finished the review

2023-02-25 20:04 UTC, zorazrr approved these changes

2023-02-25 20:09 UTC, zorazrr commented on src/components/Buttons/PrimaryButton.tsx
> +const PrimaryButton = ({ text, link }: ButtonProps) => {
One last thing, for consistency, we want to maintain the same type def format across components. Check out [NavButton](https://github.com/toriis-portal/toriis/blob/main/src/components/NavButton.tsx) for instance. We'd want to do something like `const PrimaryButton: FC<ButtonProps> = ({ text, link }) => {` here.

2023-02-25 23:48 UTC, merged