Create EPA Metrics Visualization
toriis-portal/toriis pull request #220
Opened 2023-08-14 19:00 UTC by eeshabarua

## Summary
This PR adds an EPA Metric Visualization below the text in the University Divestments section of the Fossil Fuels -> Why Divest? page, consisting of a grid of EmissionsCards with hard-coded props for now.

Closes #209 

## Changes

- Create EmissionsCard components

## Screenshots
<img width="1440" alt="image" src="https://github.com/toriis-portal/toriis/assets/61480751/0ff2e168-c122-42bc-a28c-1e6425f42ba3">

2023-08-14 19:04 UTC, eeshabarua commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +        </div>
@eeshabarua localize to json object and loop

2023-08-14 20:42 UTC, kennykos requested changes
This is looking really good so far, just a few small changes and we should be good to go.

2023-08-14 20:42 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +      <h2 className="p-2 font-bold">{title}:</h2>
```suggestion
      <h2 className="p-2 subheader-1">{title}:</h2>
```

The Figma uses graph-ff-condensed font here, which is in the repo as `subheader-1` (this is a new change since you've last been here :smile: )

2023-08-14 20:42 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +            )}
We want the metric to be centered in the box and use that graph-ff-condensed font (`subheader-1`)

2023-08-14 20:42 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +          <Icon type={type} />
We also want the Icon to be centered in the box as per the figma

2023-08-14 20:42 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          ></HighlightedTitle>
Once #213 closes and is merged in to this pr, we will be able to use `UnderlinedTitle` here, but we will have to alter it a bit (I can help with that) by adding an option for a slight offset on the underline and a graph-ff-condensed font option to accurately reflect the figma

![image](https://github.com/toriis-portal/toriis/assets/73120774/e0f7a355-054d-4035-88fc-42745e33d268)

2023-08-14 20:42 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +      <div className={clsx('rounded-md border-2 ', `border-${color}`)}>
The border colors are not showing on the vercel dev deployment (or on my local deployment for that matter)

![image](https://github.com/toriis-portal/toriis/assets/73120774/c23e04c9-6442-4c02-8143-58cdb4768608)

2023-08-14 20:42 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +      icon = <GlobeAmericasIcon />
As discussed in our meeting, lets switch these out for the origional [unicon icons](https://icon-sets.iconify.design/uil/)

2023-08-14 21:59 UTC, eeshabarua commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          ></HighlightedTitle>
Gotcha gotcha, I'll just wait this out then

2023-08-14 22:00 UTC, eeshabarua commented on src/components/card/EmissionsCard.tsx
> +      <div className={clsx('rounded-md border-2 ', `border-${color}`)}>
I was facing this problem too locally and it somehow fixed itself.. i'm not sure how why the colors in the ts config file aren't being recognized. let me ask zora bc i think something similar happened earlier this year

2023-08-15 00:05 UTC, kennykos requested changes
Let's keep investigating how to get the card's to stack for mobile, maybe @zorazrr has advice for this as well.

2023-08-15 00:11 UTC, kennykos commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="grid w-5/6 grid-cols-2 gap-x-12">
[https://tailwindcss.com/docs/responsive-design](https://tailwindcss.com/docs/responsive-design)

2023-08-16 02:53 UTC, eeshabarua commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="grid w-5/6 grid-cols-2 gap-x-12">
Oooh I see now, thanks!

2023-08-16 13:21 UTC, kennykos requested changes
With these small changes we should be good to go!

2023-08-16 13:21 UTC, kennykos commented on src/components/card/EmissionsCard.tsx
> +          <div className="text-lg leading-5">{description}</div>
```suggestion
        <div className="flex items-center justify-between py-4">
          <div className="flex items-center">
            <div
              className={clsx('ml-4 flex items-center justify-center', {
                'bg-clementine/20': color === 'pumpkin',
                'bg-lightBlue': color === 'brightTeal',
              })}
            >
              <text className="h-6 min-w-[120px] text-center text-xl font-black">
                {metric}
              </text>
            </div>
            <div className="ml-4 text-lg leading-5">{description}</div>
          </div>
```

This will help keep all the icons aligned as so
![image](https://github.com/toriis-portal/toriis/assets/73120774/172fb7ef-7b0e-4962-9f79-35cc37489017)

Instead of the unaligned current version
![image](https://github.com/toriis-portal/toriis/assets/73120774/fc9d2761-688c-40fe-b525-9f36161cace8)

2023-08-16 14:27 UTC, eeshabarua commented on src/sections/fossil-fuel/UniversityInvestments.tsx
> +          <div className="grid w-5/6 md:grid-cols-2 md:gap-x-12">
Ooh yeah that makes perfect sense

2023-08-16 14:50 UTC, kennykos approved these changes
Looks great to me!

2023-08-16 14:51 UTC, merged