Update Take Action Page With Our Requests and Responding to Pushback
toriis-portal/toriis pull request #223
Opened 2023-08-15 18:48 UTC by kennykos

## Summary

Closes #221, #222 

Update Take Action Page to have Our Request and Responding to Pushback sections, while making the text on the page more mobile responsive.

## Changes

- Add Our Request
- Add Responding to Pushback
- Add Conclusion Section
- Change padding for text, and make padding responsive to mobile viewing

## Screenshots

![image](https://github.com/toriis-portal/toriis/assets/73120774/e9418cb6-5ef2-4dca-8e71-b85b073a287d)
![image](https://github.com/toriis-portal/toriis/assets/73120774/f94528e8-644e-4e9c-909d-bbff6b8d511c)
![image](https://github.com/toriis-portal/toriis/assets/73120774/c69fe990-5769-4953-88ae-6045a0b89a44)
![image](https://github.com/toriis-portal/toriis/assets/73120774/022854b5-2609-428a-9a26-40e0ff953c41)

2023-08-15 23:55 UTC, zorazrr requested changes
Some redundant elements

2023-08-15 23:55 UTC, zorazrr commented on src/components/accordion/RequestAccordion.tsx
> +  color?: 'lightBlue'
```suggestion
  color?: string
```

2023-08-15 23:55 UTC, zorazrr commented on src/pages/take-action/index.tsx
>      // { path: 'momentum', text: 'Continue the Momentum' },
Maybe remove if unused, otherwise add a `// TODO:`

2023-08-15 23:55 UTC, zorazrr commented on src/sections/index.tsx
> +  OpenLetterConclusion as Conclusion,
Not sure why the `as` here are necessary?

2023-08-15 23:55 UTC, zorazrr commented on src/sections/take-action/conclusion.tsx
> +  }
Is this query necessary here? Seems like no data is used in this page.

2023-08-15 23:55 UTC, zorazrr commented on src/sections/take-action/responding-to-pushback.tsx
This is unrelated to the code but is it necessary to have two duplicate sections? Definitely not the expert here so just wondering bc of the amount of duplicate code.

2023-08-16 00:23 UTC, kennykos commented on src/sections/take-action/responding-to-pushback.tsx
I added conclusion to the letter class, let me know if you like that better.

2023-08-17 12:52 UTC, kennykos commented on src/sections/take-action/responding-to-pushback.tsx
Ok we settled on just having the conclusion before the requests so everything is back to normal

2023-08-18 00:44 UTC, zorazrr commented on src/sections/take-action/responding-to-pushback.tsx
If we are not using this should we delete this component?

2023-08-18 01:02 UTC, kennykos commented on src/sections/take-action/responding-to-pushback.tsx
agreed, fixed it!

2023-08-18 02:10 UTC, kennykos commented on src/sections/take-action/responding-to-pushback.tsx
done

2023-08-18 03:05 UTC, zorazrr commented on src/pages/take-action/index.tsx
> +  const respondingToPushbackEntries = homeEntries['response']
Laaaaast thing maybe delete the entries here as well

2023-08-18 03:18 UTC, kennykos commented on src/pages/take-action/index.tsx
> +  const respondingToPushbackEntries = homeEntries['response']
ok, got the last one, hopefully that's all :pray:

2023-08-18 03:41 UTC, zorazrr commented on src/pages/take-action/index.tsx
> +  respondingToPushbackEntries: RefuteResponseEntry[]
```suggestion
```

2023-08-18 03:41 UTC, zorazrr commented on src/pages/take-action/index.tsx
> +  RefuteResponseEntry,
```suggestion
```

2023-08-18 03:42 UTC, zorazrr approved these changes

2023-08-18 03:45 UTC, merged