Make primary navbar changes for mobile view.
toriis-portal/toriis pull request #230
Opened 2023-08-19 13:44 UTC by lizageorge

## Summary

## Changes

- Made primary navbar sticky on mobile only
- Styled Navbar.Collapse (the popout) colors to match design
- Tried making the popout overlap all else and take up full screen, but it's exacerbating the weird right gap issue (see below) 

## Screenshots

https://github.com/toriis-portal/toriis/assets/20449375/73d1705b-b172-4843-97b1-3f3fe3e293cf

2024-01-04 02:07 UTC, eeshabarua requested changes
ahhh awesome Liza! minor bug with navbar scroll, but otherwise looking great :D

2024-01-04 02:07 UTC, eeshabarua commented on src/components/navigation/SecondaryNavBar.tsx
> +    <nav className="center top-0 z-40 hidden bg-darkTeal py-2.5 md:sticky md:block ">
I'm not able to see the secondary nav bars once in mobile view, is that part of this PR?

2024-01-04 02:07 UTC, eeshabarua commented on src/pages/_app.tsx
> +        <main className="body-bold flex flex-col overflow-hidden">
nice right-hand margin fix! but i noticed this changes the navbar behavior on scroll down 

main:
<img width="374" alt="image" src="https://github.com/toriis-portal/toriis/assets/61480751/46337fbd-fbd5-4408-95d6-e39a7b828273">
overflow-hidden:
<img width="374" alt="image" src="https://github.com/toriis-portal/toriis/assets/61480751/207137d2-b7b1-4716-8a61-abe9cdc18129">

2024-01-07 03:59 UTC, lizageorge commented on src/components/navigation/SecondaryNavBar.tsx
> +    <nav className="center top-0 z-40 hidden bg-darkTeal py-2.5 md:sticky md:block ">
The mobile Figma design does include a drop-down menu for each page within this navbar. But to display the sections of each page for *all* pages (not just the current one) would be a pretty involved process because currently, that information is only in each page. So we'd have to either hard code the sections in the central SecondaryNavBar component (like in Primary Navbar), or find another way to pass that state up.

I can address this in a future issue, but Faith agreed that we can merge these changes in for now. 

Btw it would be pretty simple to just display the sections for only the currently open page in the current mobile navbar, similar to how Faith designed it. The tricky part is just allowing a user to navigate to a sub-section of another page instead of just the start of another page. Wdyt, do you think that's worth it?

2024-01-07 04:05 UTC, lizageorge commented on src/pages/_app.tsx
> +        <main className="body-bold flex flex-col overflow-hidden">
Shucks yea I just realized this messes with *all* sticky elements throughout the site. Lemme try fixing this some other way

2024-01-08 02:13 UTC, lizageorge commented on src/pages/_app.tsx
> +        <main className="body-bold flex flex-col overflow-hidden">
Fixed it!

https://github.com/toriis-portal/toriis/assets/20449375/a5d3eb9d-a44c-4e7c-9c1f-435b27b413f5

2024-01-10 04:20 UTC, eeshabarua approved these changes
Liza it looks great!!!

2024-01-24 21:34 UTC, merged