Create investment router with getInvestments procedure
toriis-portal/toriis pull request #31
Opened 2023-02-28 00:17 UTC by masgras2

## Summary

Creates infinite query to query investment and company data
Closes #4 

## Changes

- lorem ipsum
- dolor
- sit amet

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`investmentRouter.getInvestments.useInfiniteQuery({ limit: number})` returns a list of investments of length number

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-04 20:46 UTC, zorazrr requested changes
Very clean! Just some small nit!

2023-03-04 20:46 UTC, zorazrr commented on src/server/api/routers/investment.ts
> +export const investmentRouter = createTRPCRouter({
Because we are grouping based on `Company` instead of `Investment` now, let's switch this to `company.ts` file, rename the router to `companyRouter`, and procedure to `getCompanies`.

2023-03-04 20:46 UTC, zorazrr commented on src/server/api/routers/investment.ts
> +        cursor: z.string().nullish(), // <-- "cursor" needs to exist, but can be any type
```suggestion
        cursor: z.string().nullish(), 
```

2023-03-04 20:46 UTC, zorazrr commented on src/pages/investments/index.tsx
> +        }}
Let's add another layer of protection, check for `hasNextPage` and `isFetchingNextPage`. Something like: 
```
<button disabled={!hasNextPage || isFetchingNextPage}></button>
```

2023-03-04 20:46 UTC, zorazrr commented on src/pages/investments/index.tsx
> +  console.log(data)
```suggestion
```

2023-03-04 20:46 UTC, zorazrr commented on src/pages/investments/index.tsx
> +              key={page.items[0]?.id || index}
Do we need `{page.items[0]?.id || index}`? Is just `index` fine?

2023-03-04 20:46 UTC, zorazrr commented on src/server/api/routers/investment.ts
> +      //temporary, can't get all the needed data
```suggestion
```

2023-03-04 21:10 UTC, lizageorge requested changes

2023-03-04 21:39 UTC, masgras2 commented on src/server/api/routers/investment.ts
> +        cursor: cursor ? { id: cursor } : undefined,
Line 20 should check the input; if the cursor is undefined the function just won't return a new cursor, but the query will otherwise complete.

2023-03-05 04:08 UTC, zorazrr approved these changes
Lgtm! Nice work!

2023-03-05 04:33 UTC, lizageorge commented on src/server/api/routers/investment.ts
> +        cursor: cursor ? { id: cursor } : undefined,
It'll complete, but the rendered result is the first `limit` results being returned again, instead of nothing new or some kind of error handling. This is what it looks like when I hardcode input to be undefined:

https://user-images.githubusercontent.com/20449375/222941747-c5624ea3-9bd6-4f10-93d2-d4c2e0bc98ad.mov

Dwbi if this isn't a likely scenario. But this seems like a situation where an invalid input could break the functionality, and so should be checked for, yk?

2023-03-05 04:35 UTC, lizageorge reviewed
Aside from the input checking, this lgtm too!

2023-03-05 04:36 UTC, lizageorge approved these changes
I hit comment instead of approve :")

2023-03-05 20:42 UTC, merged