Landing Page
toriis-portal/toriis pull request #32
Opened 2023-02-28 01:37 UTC by eeshabarua

## Summary

Creating a tRPC procedure to aggregate data and display for the landing section of the home page!

Closes #8 

## Changes

- Created public procedure
- Recharts -> Apex Charts
- useState and useEffect handle states for chart series/labels

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

2023-03-04 20:00 UTC, 21xiaofanli commented on src/sections/Landing.tsx
> +  const landingHeader = clsx('text-4xl font-medium')
Could combine firstLetter and landingHeader to be conditional, up to u tho

2023-03-04 20:14 UTC, zorazrr requested changes
Chart is so beautiful!

2023-03-04 20:14 UTC, zorazrr commented on src/sections/Landing.tsx
> +            <br></br>
Nit:
```suggestion
            <br/>
```

2023-03-04 20:14 UTC, zorazrr commented on src/sections/Landing.tsx
> +    colors: ['#FFA902', '#E6F0FA', '#FF6112', '#17292E', '#0F81E8'],
Let's delete lightBlue from here for now because the text color does not show up.

2023-03-04 20:14 UTC, zorazrr commented on src/sections/Landing.tsx
> +                text={textData[6] ? textData[6] : 'Loading'}
```suggestion
                text="More about Fossil Fuels"
```
The text in the primary buttons here can be hard-coded.

2023-03-04 20:24 UTC, eeshabarua commented on src/sections/Landing.tsx
> +          <div>
oh yeah! this is the container for the text and button

2023-03-04 20:37 UTC, eeshabarua commented on src/info/home.json
> +  "landingText": {
Gotcha!

2023-03-04 21:07 UTC, daniel-moon32 requested changes
Looks good! Just a couple nitpicks

2023-03-04 21:07 UTC, daniel-moon32 commented on src/sections/Landing.tsx
> +    colors: ['#FFA902', '#FF6112', '#17292E', '#0F81E8'],
I don't know if these colors are all from the design, but the light blue is really hard to read with white text

2023-03-04 21:07 UTC, daniel-moon32 commented on src/sections/Landing.tsx
> +          <span className={firstLetter}>Transparent</span>
I think you can extract this into it's own component it's a bit weird to have all this repeating code

2023-03-04 23:36 UTC, zorazrr commented on src/sections/Landing.tsx
> +  const labels: string[] = source.data.map((dataKey) => {
Another nit, the two map functions could be simplified to 
```
  const labels: string[] = source.data.map((dataKey) => dataKey.sector)
```

2023-03-05 05:04 UTC, zorazrr commented on src/sections/Landing.tsx
> +              <PrimaryButton text="More About Fossil Fuels" link="" />
Let's link this to `/fossil-fuel`

2023-03-05 05:05 UTC, zorazrr commented on src/sections/Landing.tsx
> +              <PrimaryButton text="Learn About Investment" link="" />
Let's link these to `/fossil-fuel` and `/investments` respectively.

2023-03-05 06:14 UTC, eeshabarua commented on src/sections/Landing.tsx
> +          <span className={firstLetter}>Transparent</span>
ahh true

2023-03-05 06:15 UTC, eeshabarua commented on src/sections/Landing.tsx
> +              <PrimaryButton text="Learn About Investment" link="" />
ooh ok

2023-03-05 06:48 UTC, zorazrr approved these changes
Looking fire! Nice work!

2023-03-05 06:52 UTC, daniel-moon32 approved these changes
Looks good!

2023-03-05 06:58 UTC, merged