Use yahoo-finance2 to retrieve company details and market values
toriis-portal/toriis pull request #33
Opened 2023-03-01 01:26 UTC by anthonycruzmacedo

## Summary

- See issue #21 #yah
- 

## Changes
- 

## Screenshots

## Requests / Responses

2023-03-08 20:25 UTC, zorazrr requested changes
Heyyy you are absolutely right that `yahooFinance` can only be used on the server side!! However, to keep the pattern consistent (sorry the issue ticket was a bit misleading), it would be good if we could use this package in a tRPC procedure and keep using `useQuery` on the frontend. So you will essentially have one single query that takes a company ticker as input and returns yahoo data as output. Additionally, let's assume that comapny `id`s passed into this endpoint are valid, so we don't need to worry about the edge case. We can also discuss more in person about how to structure this!

2023-03-09 23:39 UTC, anthonycruzmacedo commented on src/components/Buttons/PrimaryButton.tsx
> +/* @typescript-eslint-disable */
I forgot to mention in PR but one commit message mentions that this will be deleted, just using to pass pre-commit hooks rn!

2023-04-03 04:40 UTC, zorazrr requested changes
The chart is looking fire 🔥🔥🔥! 
There are some small changes to notice here and there. Also make sure linter is passing and that you merge main before requesting review.
Other than those it looks really good! Great work!

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      console.log('INPUT: ' + input.id)
```suggestion
```

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +  getCompanyData: publicProcedure
Nit: naming - potentially `getCompanyFinanceData`

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +          code: 'INTERNAL_SERVER_ERROR',
`NOT_FOUND` might be good here?

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      if (query === 'NO_TICKER_FOUND') {
So with the new database updates, there is a chance where ticker could be `null`, so let's check for `null` instead of `NO_TICKER_FOUND` here.

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      }
Since this is a constant value, can we move it to the top of the file? Similar to how [ESG router is doing it](https://github.com/toriis-portal/toriis/blob/main/src/server/api/routers/esg.ts#L15) for `MAX_API_CALLS`. In the future we might want to clean everything up into a constants file, but moving it to top is fine for now.

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      const ret = yahooFinance.historical(query, options)
Better naming of `ret` would be appreciated.

2023-04-03 04:40 UTC, zorazrr commented on src/server/api/routers/company.ts
> +      const query: string = company.ticker
Better naming of `query` would be appreciated.

2023-04-03 04:40 UTC, zorazrr commented on src/components/Charts/InvestmentDetailsChart.tsx
> +      (obj: HistoricalRowHistory) => ({ x: obj.date, y: obj.close }),
Nit. naming of `obj` could be `history` or sth.

2023-04-03 04:40 UTC, zorazrr commented on src/components/Charts/InvestmentDetailsChart.tsx
> +            max: new Date().getTime(),
Maybe we should do something like `chartData.at(-1)?.x.getTime()` here, not exactly sure if the current date will match the latest date of what we fetch from the Yahoo Finance API.

2023-04-03 04:40 UTC, zorazrr commented on src/components/Charts/InvestmentDetailsChart.tsx
> +      },
Since we are not displaying markers, do we need to explicitly state size 0 here?

2023-04-03 22:25 UTC, anthonycruzmacedo commented on src/components/Charts/InvestmentDetailsChart.tsx
> +        {!!chartData && (
You're right, lots of these checks were from debugging so I'll  make sure to clean up checks!

2023-04-03 22:59 UTC, anthonycruzmacedo commented on src/components/Charts/InvestmentDetailsChart.tsx
> +            max: new Date().getTime(),
deletin xaxis property, auto sets to greatest x value

2023-04-03 23:00 UTC, anthonycruzmacedo commented on src/components/Charts/InvestmentDetailsChart.tsx
> +      (obj: HistoricalRowHistory) => ({ x: obj.date, y: obj.close }),
renamed to history

2023-04-03 23:02 UTC, anthonycruzmacedo commented on src/server/api/routers/company.ts
> +      const query: string = company.ticker
renamed to companyTicker

2023-04-03 23:03 UTC, anthonycruzmacedo commented on src/components/Charts/InvestmentDetailsChart.tsx
> +      </>
Will not display section (title & chart) if no ticker found / error occurs

2023-04-03 23:11 UTC, anthonycruzmacedo commented on src/components/Charts/InvestmentDetailsChart.tsx
> +}
Temp error message, chart is now conditionally displayed

2023-04-07 13:46 UTC, zorazrr requested changes
Looks good! 
Getting rid of some of the comments and we are good to go!

2023-04-07 13:46 UTC, zorazrr commented on src/components/Charts/FinanceBrushChart.tsx
> +  // )
```suggestion
```

2023-04-07 13:46 UTC, zorazrr commented on src/components/Charts/FinanceBrushChart.tsx
> +          // labels={labels}
```suggestion
```

2023-04-07 13:46 UTC, zorazrr commented on src/server/api/routers/company.ts
> +  // then query yahoo-finance with ticker
```suggestion
```

2023-04-08 20:46 UTC, zorazrr commented on src/server/api/routers/company.ts
> +import type { Company } from '@prisma/client'
Didn't notice this last time but this can be grouped with `import type { Investment } from '@prisma/client'`
`

2023-04-08 20:49 UTC, zorazrr approved these changes

2023-04-08 21:01 UTC, merged