Add handling of bad requests to ESG api
toriis-portal/toriis pull request #34
Opened 2023-03-02 21:04 UTC by daniel-moon32

## Summary

Description of PR here...
Closes #85, Closes #22

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-04 05:03 UTC, zorazrr requested changes
Lgtm except for a small edge case 🫡
This is beautiful tysm Daniel the goat 🐐

2023-03-04 05:03 UTC, zorazrr commented on src/server/api/routers/esg.ts
> +          if (isErrorMessage(api_res) || !api_res[0]) {
The daily-limit-reached error would also fall under this case, and a corresponding bad ticker would be created where the ticker is not necessarily bad. So we might want to add another layer to check for the error `"Specified argument was out of the range of valid values. (Parameter 'You've reached your daily limit')"` and exit.

2023-03-04 23:19 UTC, amit-sawhney reviewed
This is good, nice query ;)

2023-03-04 23:19 UTC, amit-sawhney commented on prisma/schema.prisma
>  model Company {
For prisma models it would probably be nice to name your variables in plural for arrays so when you are using them it's clear what is happening

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +interface errorMessage {
Interfaces should be capitalized

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +  "Specified argument was out of the range of valid values. (Parameter 'You've reached your daily limit')"
@zorazrr we talked about string storage ideas (not necessary just ideation)

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +    }
Consider using a wrapper Config "class" or wrapper to throw errors if your application is run without your environment variable  rather than just printing a string.

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +      const startIndexCompany = await getFirstCompany(ctx)
this naming is a lil jank lol

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +    const companiesRaw = await ctx.prisma.eSGIndex.aggregateRaw({
absolute w

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +      (company: { _id: { $oid: string }; ticker: string }) => {
Maybe add a comment about what the use of ticker and oid is. Tbh probably just comment this query a lot because it is really beefy and will be hard to maintain in the future if we forget.

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +    console.log(cleanedCompanies.length)
Remove console.logs

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +            let res
give this an explicit default value lol

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +            let res
probably `null`

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +          const api_res = await consumeExternalApi<ESG[]>(url)
Since we have an array of async operations we can use ```await Promise.all()``` rather than awaiting in each loop

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +              res = await ctx.prisma.eSG.update({
why is this ```eSG``` is this prisma??? 😭

2023-03-04 23:19 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +          const api_res = await consumeExternalApi<ESG[]>(url)
wait okay i see what you are doing, it might be better to do this in stages. So first go through and call the API a number of times and use ```await Promise.all``` and then after getting all of the responses you can parse the results and update things accordingly. a little cleaner than this approach.

2023-03-04 23:25 UTC, zorazrr commented on src/server/api/routers/esg.ts
> +            if (index === MAX_API_CALLS) {
Should this be `index === MAX_API_CALLS - 1` because it's 0-indexed?

2023-03-04 23:26 UTC, zorazrr commented on src/server/api/routers/esg.ts
> +            if (index === MAX_API_CALLS) {
Don't think `ESGIndex` is updating as expected.

2023-03-09 23:59 UTC, amit-sawhney reviewed
small nits but i think everything looks good

2023-03-09 23:59 UTC, amit-sawhney commented on prisma/schema.prisma
> +  ESGBadTicker ESGBadTicker[]
Same comment about maybe making these have plural names

2023-03-09 23:59 UTC, amit-sawhney commented on prisma/schema.prisma
> +model ESGBadTicker {
Maybe add a comment about what this model is when using loosely defined terms like "Bad"

2023-03-09 23:59 UTC, amit-sawhney commented on src/components/Buttons/ToTopButton.tsx
> +interface animateScrollType {
Capitalize and don't end an interface with "Type" ideally.

2023-03-09 23:59 UTC, amit-sawhney commented on src/components/Buttons/ToTopButton.tsx
> +    options: unknown,
do we really not know what these are? i feel like they are gonna be a string or smth

2023-03-09 23:59 UTC, amit-sawhney commented on src/components/Selects/Select.tsx
> +  }, [isOpen, onOpen])
ty

2023-03-09 23:59 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +interface errorMessage {
capitalize

2023-03-09 23:59 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +  console.log(company)
remove console.log

2023-03-09 23:59 UTC, amit-sawhney commented on src/server/api/routers/esg.ts
> +      })()
wait is this calling a function after everything?!!!! or is this just leftovers

2023-03-10 00:05 UTC, amit-sawhney commented
@daniel-moon32 maybe small edit to PR: 

> In this query we start from esgIndex and join with the Company collection. We then union this with the first 50 and limit the total to 50. This ensures that we can get wraparound.

The query works as follows: 

1. In this query we acquire all of the companies with an `_id` greater than or equal to the stored esgIndex metadata. 
2. The data is parsed through mongodb aggregation to reduce the objects to obtain only the `_id`s, truncating extra data in the documents. 
3. The query is unioned with a query that acquires the first 50 ids in the database.
4. The number of results is limited to `50` results.

The purpose of this process is maximize the amount of queries that can be run a day on the free plan and wrap around the database when the EsgIndex is near the end of the table.

2023-03-10 00:11 UTC, daniel-moon32 commented on src/server/api/routers/esg.ts
> +      })()
This is calling the function

2023-03-10 00:12 UTC, daniel-moon32 commented on src/components/Buttons/ToTopButton.tsx
> +    options: unknown,
The type is any, so I'm not too sure

2023-03-11 01:55 UTC, zorazrr approved these changes

2023-03-11 01:56 UTC, merged