Xl our request
toriis-portal/toriis pull request #41
Opened 2023-03-03 05:18 UTC by 21xiaofanli

## Summary
Create the Requests Landing Page 
Description of PR here...
 Closes #10

## Changes

- Added OurRequestSection and DropDownMenu
- Added a new file that defines a props component
- Added the Section into index.tsx

## Screenshots

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/91353008/222637531-d3687045-74ae-4612-ba2d-30d0af38c98c.png">
## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-03 15:34 UTC, zorazrr requested changes
The drop down cards are looking 🔥🔥🔥!

There are some styling adjustments. Overall would be good to 
- Double check/inspect Figma a bit more in the future! 
- Avoid unnecessary wrappings of divs 
- Read through the code and clean up comments/console.logs 

Exciting to see the home page coming together ✨!

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +              {item.list.map((bullet) => (
```suggestion
              {item.list.map((bullet, index) => (
```

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +              {item.list.map((bullet) => (
Notice that, without the `index` here, this error would pop up in console: 
```
next-dev.js?3515:20 Warning: Encountered two children with the same key, `2`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +              {item.sublist.map((bullet) => (
```suggestion
              {item.sublist.map((bullet, index) => (
```

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +              {item.sublist.map((bullet) => (
Same as above^^

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +        ) : null}
Nit. We could do `{open && <div>stuff</div>}` instead of `{open ? <div>stuff</div> : null}`.

2023-03-03 15:34 UTC, zorazrr commented on src/types/ourRequest.ts
> +export interface Props {
Nice interface definition here :).

2023-03-03 15:34 UTC, zorazrr commented on src/components/Displays/DropDownCard.tsx
> +          'w-10/12 content-center rounded-xl bg-white shadow-lg',
This is a kinda hacky way to center it, but getting rid of `w-10/12` would do it. Additionally, not sure if shadow is needed here? Check [Figma](https://www.figma.com/file/PFCGAeZzwLEyzNaovh6Zfq/Toriis?node-id=3%3A1346&t=o6rHcS19acwkuGgs-0).

2023-03-04 19:54 UTC, eeshabarua approved these changes
This looks amazing!!

2023-03-04 19:54 UTC, eeshabarua commented on src/components/Displays/DropDownCard.tsx
> +      className={clsx('mb-6 ml-8 mr-20 content-center rounded-xl bg-white', {
the clsx is nice!

2023-03-04 19:54 UTC, eeshabarua commented on src/components/Displays/DropDownCard.tsx
> +          <ol className="list-[lower-roman] pl-24 pr-8">
bullets in tailwind niiice

2023-03-05 01:51 UTC, zorazrr approved these changes

2023-03-05 03:53 UTC, merged