Timeline section
toriis-portal/toriis pull request #43
Opened 2023-03-05 09:45 UTC by daniel-moon32

## Summary
Create timeline items
Closes #23 

## Changes

- Add JSON data
- Create dynamically generated timeline

## Screenshots
![image](https://user-images.githubusercontent.com/36148173/222953241-baa8a1c0-a5f0-4a0c-a0b3-1523f5d6de74.png)

2023-03-05 16:09 UTC, zorazrr requested changes
Heyyyyyy 3:45am-PR the timeline is very cool! Several things 
- We should extract the components a bit more to make things modular 
- Let's use `clsx` for an intuitive classname 
- Misc styling, margin, padding, height stuff 
Otherwise it's gReAt.

2023-03-05 16:09 UTC, zorazrr commented on src/sections/Timeline.tsx
> +                {!isLeft ? (
Can we extract the little orange line into its own component, where we pass in `isLeft`? We can use `flex-row-reverse` conditionally in its wrapper div. Something like this: 
```
<div
  className={clsx("border-4 relative float-right flex w-full", {
    "flex-row-reverse": isLeft,
  })}
>
  <LittleLine isLeft={isLeft} />
  <div
    className={`basis-5/12 rounded-lg bg-darkTeal p-2`}
  >
    <p className="text-center text-[40px] text-white">
      {item.date}
    </p>
  </div>
</div>
```
This way we can get rid of the two `isLeft` conditionals and make this component much shorter.

2023-03-05 16:09 UTC, zorazrr commented on src/sections/Timeline.tsx
> +                    false,
Additionally, for these conditional classnames, I feel like `clsx` makes it more intuitive (see [the nav buttons](https://github.com/toriis-portal/toriis/blob/cb4f1ca052d38c5239ff0a822b6a3154441617a5/src/components/Buttons/NavButton.tsx#L20-L21) for instance). What do you think?

2023-03-05 16:09 UTC, zorazrr commented on src/sections/Timeline.tsx
> +                )}-28 text-${getDirection(!isLeft, false)} `}
Maybe use `clsx` here :) ?

2023-03-05 16:09 UTC, zorazrr commented on src/sections/Timeline.tsx
> +    <div className="relative mx-96 h-[400px] min-h-screen border-spacing-1 text-6xl">
```suggestion
    <div className="relative mx-12 min-h-screen border-spacing-1 text-6xl">
```

2023-03-05 16:11 UTC, zorazrr commented on src/sections/Timeline.tsx
> +                className={`p-10 m${getDirection(
```suggestion
                className={`px-10 py-2 m${getDirection(
```

2023-03-05 17:39 UTC, daniel-moon32 commented on src/pages/home/index.tsx
> +          data={jsonData.timeline as TimelineEntry[]}
I think the type is getting inferred here, but it's not recognizing it as the type I want (hence the explicity casting)

2023-03-05 17:42 UTC, daniel-moon32 commented on src/sections/Timeline.tsx
> +    <div className="relative mx-96 h-[400px] min-h-screen border-spacing-1 text-6xl">
I don't know if this is a screen ratio thing, but doesn't this break the current look?

2023-03-05 17:48 UTC, zorazrr commented on src/sections/Timeline.tsx
> +    <div className="relative mx-96 h-[400px] min-h-screen border-spacing-1 text-6xl">
Huhhh it might be a screen ratio thing it looked kinda wack on my screen.

2023-03-06 21:08 UTC, zorazrr requested changes

2023-03-06 21:08 UTC, zorazrr commented on src/sections/Timeline.tsx
> +        <div className="flex w-1/2 flex-col">
Actually jk I see the rationale for using `<Spacer />` .

2023-03-06 21:08 UTC, zorazrr commented on src/sections/Timeline.tsx
> +    <div className="relative mx-64 min-h-screen border-spacing-1 text-6xl">
```suggestion
    <div className="relative mx-[10%] min-h-screen border-spacing-1 text-6xl">
```
To make it slightly more responsive :).

2023-03-06 21:08 UTC, zorazrr commented on src/sections/Timeline.tsx
> +      <HighlightedTitle title={text} />
`<HighlightedTitle/>` should stay outside of this `div` to make it consistent with other sections.

2023-03-09 02:59 UTC, zorazrr approved these changes

2023-03-09 03:21 UTC, merged