Donut Chart Final Touches 💅🏾
toriis-portal/toriis pull request #53
Opened 2023-03-09 07:18 UTC by eeshabarua

## Summary

Description of PR here...
Closes #45 

## Changes

- Add styling to 's' in the Capitalized Header
- take away react-scroll offset
- make adjustments to donut chart

## Screenshots

![image](https://user-images.githubusercontent.com/61480751/223948378-94557a6d-b79d-48a4-a95f-e6bec73298ed.png)

## Requests / Responses

2023-03-09 20:50 UTC, zorazrr requested changes
Love the functional programming uses here 💗 !!! 
Several things: 
- Let's extract these small map reduce functions into one helper function to transform the data 
- Let's look into more efficient ways of reducing data 
- Let's check with Joos if `None` should be displayed at all 

Great work!

2023-03-09 20:50 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +    .filter((item) => item.count < 23)
Let's not hard-code the value 23 here! We could obtain the threshold with 
```js
  const total = pairs.reduce((sum, item) => sum + item.count, 0);
  const threshold = total * 0.05;
```

2023-03-09 20:50 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +
Can we extract everything up to this point into a single helper function that handles all the necessary data transformations?

2023-03-09 20:50 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +  interface dataObj {
Variable naming~!

2023-03-09 20:50 UTC, zorazrr commented on src/components/Nav/SecondaryNavBar.tsx
> +                // offset={-35}
Directly deleting this is fine!

2023-03-09 20:50 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +  newCount += pairs.find((item) => item.label === 'NONE')?.count ?? 0
On second thought, it might be beneficial to directly remove companies with sector `NONE` from the chart? Check with @jocelynxu01.

2023-03-09 20:50 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +    item.count < 23 || item.label == 'NONE'
We can combine this map function with where we are calculating `newCount` with `filter` followed by a `reduce`! For example: 
```js
// This filtered array gives us everything that is above threshold 
const filtered = arr.filter((item) => item.count >= threshold);
// The first filter picks out the items below threshold, and reduce calculate the sum of those. 
const newCount = arr.filter((item) => item.count < threshold).reduce((sum, item) => sum + item.count, 0);
// Then we can directly push to filtered array 
filtered.push({ label: 'OTHER', count: { label: 'OTHER', count: aggregated } })
```
A good use of filter/reduce can make the function cleaner and largely reduce the length of the code!

2023-03-09 21:00 UTC, eeshabarua commented on src/components/Charts/LandingDonutChart.tsx
> +  newCount += pairs.find((item) => item.label === 'NONE')?.count ?? 0
Oooh okay! Joos says we can keep it

2023-03-09 23:11 UTC, eeshabarua commented on src/components/Charts/LandingDonutChart.tsx
> +
use cleaner one-liners where possible

2023-03-11 02:08 UTC, zorazrr approved these changes
Very nice!

2023-03-11 02:08 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +  interface sector {
Let's move interfaces to the top of the file (maybe right before the line `const LandingDonutChart: FC = () => {
`)!

2023-03-11 02:08 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
> +     * Set total to calculate the threshold
The comments are really helpful in understanding what each step of the function does, but when we actually merge it in, it would be good to just have one comment regarding the entire function to keep things short and clean.

2023-03-11 14:28 UTC, merged