Load More Button
toriis-portal/toriis pull request #55
Opened 2023-03-09 23:22 UTC by lizageorge

## Summary

Creates Load More Button for Investments page
Closes #40 

## Changes

- Load More Button
- Disabled and Active Styling

## Screenshots

<img width="665" alt="image" src="https://user-images.githubusercontent.com/20449375/224182833-8f4e03ec-59ec-4999-938f-2659eed210a3.png">
## Requests / Responses

https://user-images.githubusercontent.com/20449375/224182886-9cf80246-2e1b-4675-b6e8-c44b931071c5.mov

2023-03-10 00:18 UTC, zorazrr requested changes
Looks good! Just some small changes.

2023-03-10 00:18 UTC, zorazrr commented on src/components/Buttons/LoadMoreButton.tsx
> +  children?: React.ReactNode
Do we need this?

2023-03-10 00:18 UTC, zorazrr commented on src/components/Buttons/LoadMoreButton.tsx
> +        'active:shadow-[-12px_12px_0px_0px] active:shadow-clementine',
When we hover, can we have the same style as well?

2023-03-20 22:02 UTC, lizageorge commented on src/components/Buttons/LoadMoreButton.tsx
> +  children?: React.ReactNode
I'm a bit confused by what you mean - are you asking if we need this interface or if we need props at all? Or a specific field within it?
This structure is a simplified version of this tutorial - [https://www.twilio.com/blog/intro-custom-button-component-typescript-react](https://www.twilio.com/blog/intro-custom-button-component-typescript-react)

2023-03-23 09:09 UTC, lizageorge commented on src/components/Buttons/LoadMoreButton.tsx
> +  children?: React.ReactNode
Nwm, turns out it is is unnecessary (the children field)

2023-03-23 15:17 UTC, zorazrr approved these changes
Looks good!

2023-03-24 02:33 UTC, merged