Integrate Contentful
toriis-portal/toriis pull request #56
Opened 2023-03-11 17:14 UTC by zorazrr

## Summary

In progress

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-15 15:53 UTC, daniel-moon32 requested changes
Just  a couple small things with naming, but otherwise looks good

2023-03-15 15:53 UTC, daniel-moon32 commented on src/info/home.json
Let's gooo no more json file

2023-03-15 15:53 UTC, daniel-moon32 commented on src/sections/home/Landing.tsx
> +  const contentfulOptions = {
More of the whacky contentful stuff. I think I get it, but for future reference you probably want a quick comment to tell people what this does.

2023-03-16 20:08 UTC, zorazrr commented on src/info/home.json
Let's gooo commenting on the entire file

2023-03-17 04:16 UTC, zorazrr commented on src/pages/home/index.tsx
> +  const ourRequestsEntries = await contentClient.get('request')
Seems that Contentful does not support get entries by multiple content types. I made it slightly better by adding a `getAllHomePageEntries` function in the newest commit. It's still making 6 requests though lol. Another option is to call `getEntries` without content type to get everything, but we might want to add content types in the future so not doing that might be the way to go.

2023-03-18 03:58 UTC, daniel-moon32 approved these changes
Looks good!

2023-03-18 04:05 UTC, merged