Add chevron logic for filter select
toriis-portal/toriis pull request #58
Opened 2023-03-11 23:13 UTC by daniel-moon32

## Summary

Description of PR here...
Closes #85, Closes #22

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-18 22:57 UTC, zorazrr requested changes
Excited to have the filtering there! 

On major thing is how the `ESG` relation impacts the entire query. See some of the comments for details, we can also discuss this a bit more. Another thing to notice is responsiveness. 

But overall it looks really good!

2023-03-18 22:57 UTC, zorazrr commented on src/server/api/routers/company.ts
> +          ESG: {
With this statement here, the query is only fetching companies that has an `ESG` entry. We want to display company info regardless of whether they have an ESG or not (double check with @jocelynxu01 on this). The implementation for this is also associated with the one-to-many v one-to-one relation so we should look into that first.

2023-03-18 22:57 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +    <div className="relative ml-10 w-60">
Maybe use percentage to set width here for better responsiveness. For now, let's be concerned with screen size up to 800px. The same goes for setting paddings/margins.

2023-03-18 22:57 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +                    <span className={clsx({ 'text-sm': isFilter })}>
```suggestion
                    <span className={clsx({ 'text-md': isFilter })}>
```
Double check Figma. Also it seems like the font is `Inter`.

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +      nextInterval[1]
This is interesting lol.

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +      nextInterval[1]
Is merging the interval really necessary though? Seems like the backend is mapping those ranges anyways.

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +          containerHeight="240px"
Huh what is `containerHeight` O_O.

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +const convertToFilterOptions = (selectedFilters: string[]) => {
Nit. Naming is a bit misleading, maybe something like `convertToFilterByOptions` or `convertToQueryInput`?

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +      <div className="flex flex-row gap-0">
Let's move this div above the data section. Additionally, when the select dropdown is opened, the dropdown should not overlap with the data section according to Figma.

2023-03-18 22:57 UTC, zorazrr commented on src/pages/investments/index.tsx
> +]
Beautiful O_O. Let's move this to the `utils` folder though.

2023-03-18 23:21 UTC, zorazrr commented
Also regarding the calling refetch every time the filter object is changed issue. We do want to address that with some debouncing, maybe in a separate issue though.

2023-03-28 19:26 UTC, zorazrr requested changes
Yay! Filters! Some styling changes.

2023-03-28 19:26 UTC, zorazrr commented on src/pages/investments/index.tsx
> +
A lot of these imports could be grouped together.

2023-03-28 19:26 UTC, zorazrr commented on src/server/api/routers/company.ts
> +          : undefined
Nit. Can these two be merged into one function potentially? Up to you though.

2023-03-28 19:26 UTC, zorazrr commented on tailwind.config.cjs
> +        '98%': '98vh',
Is this supposed to be `vw` instead of `vh`? Looks like these definitions are used with width but now width changes based on screen height.

2023-03-28 19:28 UTC, daniel-moon32 commented on src/components/Selects/Select.tsx
> +  containerHeight?: string // Only handles 1/4, 1/2, 3/4
It's controlling the max height of the dropdown. I think the only reason that it's used in the industry is because it has the longest list and otherwise it's set to fit content by default.

2023-03-28 19:29 UTC, zorazrr commented on src/components/Selects/Select.tsx
> +  containerHeight?: string // Only handles 1/4, 1/2, 3/4
I see I see

2023-04-07 04:26 UTC, zorazrr approved these changes

2023-04-07 04:26 UTC, zorazrr commented on src/server/api/routers/company.ts
> +  console.log(sortByNetAssetVal, sortByEnvGrade)
```suggestion
```

2023-04-07 04:26 UTC, zorazrr commented on src/server/api/routers/company.ts
> +    console.log('sortByEnvGrade', sortByEnvGrade)
```suggestion
```

2023-04-07 04:26 UTC, zorazrr commented on src/server/api/routers/company.ts
> +    return { name: 'asc' }
```suggestion
    return { }
```

2023-04-07 04:45 UTC, merged