Investment Table
toriis-portal/toriis pull request #62
Opened 2023-03-17 00:04 UTC by daniel-moon32

## Summary

Description of PR here...
Closes #52 

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses

`userRouter.getUser.useQuery({id: string})` returns a list of users

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

2023-03-19 16:16 UTC, zorazrr requested changes
Looks good! Just some type defs and styling nits.

2023-03-19 16:16 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +      }),
There should be a more generic way to handle this. 
- Access property value of the object with something like `a[object[0]]`
- Compare using `>` instead of `-` (which complains about stuff not being a number) 

Ask Chatgpt for this it gives a decent answer lol.

2023-03-19 16:16 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +          <th className="w-1/6 border-x-2 border-white">
Noticed that there are a lot of stye definitions that are the same. We can potentially extract it into a variable 
```js
const tableHeadStyle = clsx("w-1/6 border-x-2 border-white")
```
and use that here. Same goes for the table cells. Maybe easier to maintain in the future.

2023-03-19 16:16 UTC, zorazrr commented on src/pages/company/[id].tsx
> +const Home = () => {
Let's name `Home` something else.

2023-03-20 22:52 UTC, daniel-moon32 commented on src/components/Table/InvestmentTable.tsx
> +      }),
I don't think the `-` matters here since the sort takes in a number and not all values have a direct comparator

2023-03-21 04:43 UTC, zorazrr approved these changes

2023-03-21 04:43 UTC, merged