Company-Specific Investments Infinite Query
toriis-portal/toriis pull request #70
Opened 2023-03-21 05:05 UTC by eeshabarua

## Summary

This procedure queries the first five investments for a Company, then uses cursor-based pagination to load more until the investments are exhausted. 
Closes #51 

## Changes
- add Results page
- console.log testing

## Screenshots

## Requests / Responses

getInvestmentsByCompany gets a list of investments, but currently the items array is empty and only nextCursor is accurate.

![image](https://user-images.githubusercontent.com/61480751/226523211-3adb73fe-76fe-4ff7-b08f-30e4f061baa7.png)

2023-03-23 17:44 UTC, masgras2 requested changes
All the code currently here looks good! The largest issue now has to do with the sorting of the table. Right now when the table is sorted (for example, with quantity low to high as shown here)...

![image](https://user-images.githubusercontent.com/111911351/227275832-0e0dec60-c6a0-4329-b86b-5c50ef133bd5.png)

...the table doesn't actually display the 5 investments with the lowest quantity. Clicking to load more shows that there is actually an investment with an intermediate quantity that hadn't been loaded into the table due to being stored later in the database.

![image](https://user-images.githubusercontent.com/111911351/227277225-6ec5ae8f-34c8-4823-862a-d5529b99c87f.png)

Ideally I think, Prisma [orderBy](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting) would be used like it is in pages/investments/index.tsx and the getInvestments procedure in companyRouter to re-query the database every time the way the table is sorted is changed. It may be easier to have this code on InvestmentTable instead of /company/[id], but that would involve giving InvestmentTable additional functionality beyond simply being a table to display investments, so I think /company/[id] makes more sense.

If sorting is considered not to be in the scope of this issue, then all that needs done is for everything from /results/index.tsx to be moved to /company/[id].tsx.

2023-03-23 17:44 UTC, masgras2 commented on src/pages/results/index.tsx
All this code should probably just be put in /company/[id], now that 64bdeaa has been merged into main.

2023-03-23 17:44 UTC, masgras2 commented on src/server/api/routers/company.ts
> +  getInvestmentByCompany: publicProcedure
Everything here looks good, the only change would be adding orderBy if we're implementing sorting in the query.

2023-03-23 18:14 UTC, zorazrr requested changes
Looks good overall! 
One major change is using dynamic `companyId` instead of hard-coding the value.

2023-03-23 18:14 UTC, zorazrr commented on src/pages/results/index.tsx
> +      <h2>{isLoading && '(loading)'}</h2>
Noticed that there is a `if (!data)` check on line 40 and another one here. Potentially these two can be merged into `if (!data || isLoading)`.

2023-03-23 18:14 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        companyId: z.string().nullish(),
Hmmm. Actually not sure about if `companyId` should be `nullish()` here, since this query relies on there being a `companyId` to search for.

2023-03-23 18:14 UTC, zorazrr commented on src/server/api/routers/company.ts
> +        companyId: z.string().nullish(),
Alternatively, we can throw a tRPC error if the `companyId` is not there (check [this](https://github.com/toriis-portal/toriis/blob/main/src/server/api/routers/esg.ts#L62) for instance).

2023-03-23 18:16 UTC, zorazrr commented
> All the code currently here looks good! The largest issue now has to do with the sorting of the table. Right now when the table is sorted (for example, with quantity low to high as shown here)...
> 
> ![image](https://user-images.githubusercontent.com/111911351/227275832-0e0dec60-c6a0-4329-b86b-5c50ef133bd5.png)
> 
> ...the table doesn't actually display the 5 investments with the lowest quantity. Clicking to load more shows that there is actually an investment with an intermediate quantity that hadn't been loaded into the table due to being stored later in the database.
> 
> ![image](https://user-images.githubusercontent.com/111911351/227277225-6ec5ae8f-34c8-4823-862a-d5529b99c87f.png)
> 
> Ideally I think, Prisma [orderBy](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting) would be used like it is in pages/investments/index.tsx and the getInvestments procedure in companyRouter to re-query the database every time the way the table is sorted is changed. It may be easier to have this code on InvestmentTable instead of /company/[id], but that would involve giving InvestmentTable additional functionality beyond simply being a table to display investments, so I think /company/[id] makes more sense.
> 
> If sorting is considered not to be in the scope of this issue, then all that needs done is for everything from /results/index.tsx to be moved to /company/[id].tsx.

Let's confirm with @jocelynxu01 on this @eeshabarua, and adjust accordingly. Currently the table uses frontend sorting to avoid hitting the DB too much.

2023-03-28 02:28 UTC, daniel-moon32 requested changes
A couple stylistic things and a bug, but otherwise looks good!

2023-03-28 02:28 UTC, daniel-moon32 commented on src/components/Table/InvestmentTable.tsx
> +              onClickUp={() => handleSortChange(['rawName', 'asc'])}
Is there a reason we are changing this from the original boolean value? My best guess is for clarity, but I find that string types are messy at best, so we need a clear reason to use it over a boolean like it was before.

2023-03-28 02:28 UTC, daniel-moon32 commented on src/pages/company/[id].tsx
> +      console.error(err)
I'll defer to @zorazrr on this, but generally you need a stronger catch than just printing to console.error when the refetch fails. Might be something to ask Jocelyn or Miranda as well.

2023-03-28 02:28 UTC, daniel-moon32 commented on src/pages/company/[id].tsx
> +  data?.pages.forEach((page) => {
generally you don't want to use forEach when you have side effects like this. It's much more preferable to use .map to make the new list instead of pushing to a new list. (feel free to ask me more about what I mean here)

2023-03-28 02:28 UTC, daniel-moon32 commented on src/pages/company/[id].tsx
> +          void fetchNextPage()
is this void necessary? I believe you should just be able to call the function?

2023-03-28 02:28 UTC, daniel-moon32 commented on src/server/api/routers/company.ts
> +          code: 'ERRNOTFOUND',
I think this is a different error code perhaps BAD_REQUEST would work better here. Check out the docs for more info: https://trpc.io/docs/server/error-handling

2023-03-28 02:28 UTC, daniel-moon32 commented on src/components/Table/InvestmentTable.tsx
> +  onSortChange: (sort: [keyof Investment, 'asc' | 'desc' | undefined]) => void
I'm not entirely convinced by this typing, I think there are probably cleaner ways to do it, but you can ignore this if you have some insight for why this is necessary.

2023-03-28 02:28 UTC, daniel-moon32 commented on src/server/api/routers/company.ts
> +          code: 'ERRNOTFOUND',
This is also why the build is failing on the vercel deployment, make sure it corresponds to one of the strings listed

2023-03-28 13:19 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +  onSortChange: (sort: [keyof Investment, 'asc' | 'desc' | undefined]) => void
LOL I told her do this. To keep it consistent with [these sorts](https://github.com/toriis-portal/toriis/blob/main/src/pages/investments/index.tsx) and also to allow the initial state to be unsorted.

2023-03-29 00:17 UTC, eeshabarua commented on src/pages/company/[id].tsx
> +          void fetchNextPage()
i believe void is necessary, otherwise a "promises must be awaited" error flares
![image](https://user-images.githubusercontent.com/61480751/228394863-9b17a671-de31-4829-93e2-76e8079211ce.png)

2023-03-31 05:24 UTC, zorazrr requested changes
Looks really clean with the backend ordering! 
There are some small clean-ups and consistency stuff that we should watch out for, but overall it is good and we are very close to merging it!

2023-03-31 05:24 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +      console.error(err)
I know we talked about error handling, don't worry about it here (for now). We likely want to figure out a unified error handling method and apply it to all procedures in the future.

2023-03-31 05:24 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +          })}
Kinda circling back to the `forEach` v `map` discussion. I realized that [this page](https://github.com/toriis-portal/toriis/blob/main/src/pages/investments/index.tsx#L110) is mapping paged data directly to components, so let's keep it consistent.

2023-03-31 05:24 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +          })}
One tricky thing is that you might want to do some math based on index and fetch limit to have alternate bg colors for rows.

2023-03-31 05:24 UTC, zorazrr commented on src/components/Table/InvestmentTable.tsx
> +      </button>
There should be a `<LoadMoreButton/>` component for this!

2023-04-01 21:38 UTC, zorazrr approved these changes
Looks good!

2023-04-01 21:49 UTC, merged