Add files for tooltip
toriis-portal/toriis pull request #75
Opened 2023-03-22 21:53 UTC by 21xiaofanli

## Summary
Create new tooltip to display more information for Company Cards.

Closes #61

## Changes

Has 4 different types of tooltips that will be displayed depending on if it is a sector, industry, net asset sum, or environmental grade.

## Screenshots

(Will insert soon)

2023-03-23 15:34 UTC, zorazrr commented
Noticed the use of React Tooltip here. We actually have a simple tailwind component library in the repo, so check out [flowbite react tooltip](https://flowbite-react.com/tooltips) :).

2023-03-27 01:08 UTC, zorazrr requested changes
The tooltips are looking great!! 
Just some small changes + adding them to the company page. 
Nice work :)

2023-03-27 01:08 UTC, zorazrr commented on src/components/Buttons/ToolTipButton.tsx
> +  child?: React.ReactNode
Currently, with `child` prop, we use this component like 
```js
<ToolTip child={<div>something</div>} />
```
If we change `child` to `children` (a special prop in React) though, we will be able to use it like 
```js
<ToolTip><div>something</div></ToolTip>
```

2023-03-27 01:08 UTC, zorazrr commented on src/components/Buttons/ToolTipButton.tsx
> +            '-translate-x-1/2 rounded border border-black bg-white',
```suggestion
            '-translate-x-1/2 rounded-xl border border-black bg-white',
```

2023-03-27 13:59 UTC, zorazrr requested changes
Great work! Some more changes and we are almost there!

2023-03-27 13:59 UTC, zorazrr commented on src/pages/company/[id].tsx
> +            </div>
Check out the [Tag Component](https://github.com/toriis-portal/toriis/blob/main/src/components/Text/Tag.tsx)! Although, I noticed the tag component is missing a `w-fit` property, so it'd be great if you could add it there as well!

2023-03-27 13:59 UTC, zorazrr commented on src/pages/company/[id].tsx
> +        </ToolTip>
Thanks for adding these in the company page, it's looking great! Could we also add the "sector, net asset sum, industry, environmental grades" tags and their corresponding text? 

![image](https://user-images.githubusercontent.com/61670566/227960495-f9d44127-78a0-40d1-9428-0b5c42bfff2c.png)

2023-03-27 13:59 UTC, zorazrr commented on src/components/index.ts
> +import Tooltip from './Tooltips/ToolTip'
Should this be `ToolTip` or `Tooltip`?

2023-03-27 13:59 UTC, zorazrr commented on src/pages/company/[id].tsx
> +import ToolTip from '../../components/Tooltips/ToolTip'
So now that `ToolTip` is exported from `src/components/index.ts`, we can group these two imports together like `import { InvestmentTable, ToolTip } from '../../components'`

2023-03-27 14:01 UTC, zorazrr commented
Another quick nit: let's name the PR title a bit more descriptively! Something like "Add tooltips to company page" would be good!

2023-03-28 02:44 UTC, daniel-moon32 requested changes
Looks good! Feel free to ignore my comment about extensibility if you have some context or info I might be missing.

2023-03-28 02:44 UTC, daniel-moon32 commented on src/components/Text/Tag.tsx
> +      className={`flex justify-center rounded-full ${backgroundColor} text-${textColor} w-fit px-[18px] py-0 text-lg font-medium`}
I think you can make this a little more extensible. Instead of having explicit props, I think you can instead just have a className prop that appends whatever styles to the end of the current styling. That way if we want to change more than just the text color and background color we can.

2023-03-28 15:57 UTC, zorazrr approved these changes

2023-03-28 20:51 UTC, daniel-moon32 approved these changes
Looks good!

2023-03-28 20:51 UTC, daniel-moon32 commented on src/components/Text/Tag.tsx
> +      className={`flex justify-center rounded-full ${className} w-fit px-[18px] py-0 text-lg font-medium`}
Beautiful!

2023-03-28 21:50 UTC, merged