Back Button
toriis-portal/toriis pull request #77
Opened 2023-03-23 21:19 UTC by eeshabarua

## Summary

It is a button : ) it goes back 

Closes #68 

## Changes

- Create button component
- Implement routing
- Implement styling

## Screenshots

![image](https://user-images.githubusercontent.com/61480751/227364949-7489352f-5290-4b83-a101-da27eebf8366.png)

2023-03-30 23:29 UTC, daniel-moon32 reviewed
Couple of minor styling issues, but looks good! Generally I would suggest looking at the build failure logs beforehand to double check any issues that you might be seeing.

2023-03-30 23:29 UTC, daniel-moon32 commented on src/components/Buttons/BackButton.tsx
> +import { ArrowBack } from '@material-ui/icons'
I think we're using hero-icons, but @zorazrr can correct me if I'm wrong

2023-03-30 23:29 UTC, daniel-moon32 commented on src/components/Buttons/BackButton.tsx
> +          'justify-centerfont-klima flex w-20 place-content-center items-center text-[18px]',
I think generally we want to stray away from using a constant text size and width

2023-03-30 23:29 UTC, daniel-moon32 commented on src/components/Buttons/BackButton.tsx
> +      <p className="font-[400]"> Back</p>
Hmm shouldn't we use text-whateversize? instead of this?

2023-03-31 05:31 UTC, zorazrr requested changes
Some small things to change!

2023-03-31 05:31 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
> +import { ArrowBack } from '@material-ui/icons'
Right, we are using [hero icons](https://heroicons.com/)^^

2023-03-31 05:31 UTC, zorazrr commented on src/pages/fossil-fuel/index.tsx
> +      <div>Fossil Fuel Page</div>
Let's add the back button to company details page (should also merge main into your branch for this) !

2023-03-31 05:31 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
Remember to export it in the [components master sheet](https://github.com/toriis-portal/toriis/blob/main/src/components/index.ts) whenever a new component is created!

2023-03-31 05:31 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
> +          'justify-centerfont-klima flex w-20 place-content-center items-center text-[18px]',
```suggestion
          'justify-center font-klima flex w-20 place-content-center items-center text-[18px]',
```

2023-04-04 03:49 UTC, zorazrr commented on src/components/Buttons/BackButton.tsx
> +      <p className="font-[400]"> Back</p>
```suggestion
      <p className="font-normal"> Back</p>
```

2023-04-04 03:54 UTC, zorazrr approved these changes
Great work!

2023-04-04 04:01 UTC, merged