Updated Donut chart to Reflect the Total Net Asset Sum per Sector
toriis-portal/toriis pull request #86
Opened 2023-03-27 22:51 UTC by 21xiaofanli

## Summary
Updated Donut chart to Reflect the Total Net Asset Sum per Sector + added title below
Description of PR here...
Closes #72

## Changes

- added title
- changed query to reflect the total net asset sum per sector

## Screenshots

<img width="539" alt="image" src="https://user-images.githubusercontent.com/91353008/228084407-bbf5b2e4-6a64-4669-8a6d-6de67a0c2450.png">## Requests / Responses

2023-03-28 02:38 UTC, daniel-moon32 requested changes
Just a few minor changes and questions. Looks good otherwise!

2023-03-28 02:38 UTC, daniel-moon32 commented on src/components/Accordions/RequestAccordion.tsx
> +        <div className="border-t-2 border-cobalt px-4 pt-6 font-inter text-base text-neutral-600 md:px-20">
I don't know if this change was supposed to be in a different PR, but I think generally you should avoid having changes across unrelated items

2023-03-28 02:38 UTC, daniel-moon32 commented on src/components/Charts/LandingDonutChart.tsx
> +    .filter((data) => data._sum.netAssetSum !== null)
Just want to double check my understanding, but is there a possibility that this value could be undefined as well?

2023-03-28 02:38 UTC, daniel-moon32 commented on src/sections/home/Landing.tsx
> +          <div className=" flex justify-center pt-2 font-inter text-xl font-semibold">
```suggestion
          <div className="flex justify-center pt-2 font-inter text-xl font-semibold">
```

2023-03-28 05:18 UTC, zorazrr requested changes

2023-03-28 05:18 UTC, zorazrr commented on src/components/Charts/LandingDonutChart.tsx
>          options={options}
Turns out that there does exist a `formatter` in Apex Chart. So let's still aggregate the displays a bit to avoid that large chunk of number. If you add something like this to the `options` here passed in: 
```js
    tooltip: {
      y: {
        formatter: function (val: number) {
          return assetAmountToString(val)
        }
      }
    },
```
Read more [in this discussion](https://github.com/apexcharts/apexcharts.js/issues/52#issuecomment-415974783)!

2023-03-30 22:08 UTC, zorazrr approved these changes

2023-03-30 22:08 UTC, merged